### ISSUE TITLE
When starting vim, or nvim, screen gets stuck at:  "⌗  Loading workspace 'hw_1_5'...  "  

### ISSUE THREAD

**Issue by sittim** [vim-ctrlspace/vim-ctrlspace#148]
# Issue:

At command prompt after executing:

``` bash
nvim
```

the following screen comes up and hangs:

![selection_052](https://cloud.githubusercontent.com/assets/8825037/10577961/1509b4ec-763d-11e5-967a-5c01d61fdf57.png)

I have to hit enter a couple times for the system to continue.  It works OK, but it is little annoying that I cannot pop in and out of vim...  (_Note: This works the same way for nvim and vim_)

**Comment by sittim** [comment]
OK, so posting the question somehow made me realize the answer.  This is due to `YouCompleteMe` plug-in, Actually underneath the YCM is looking for confirmation to load the `.ycm_extra_conf.py`, but for some reason the question does not show up.  So one of the solutions is to turn off the confirmation, by:

```viml
let g:ycm_confirm_extra_conf = 0
```

Is there any way to let ctrlspace to show that question?

**Comment by szw** [comment]
I remember some issues related to this topic with an old session mechanics in Vim-CtrlSpace. But nowadays the plugin uses just standard Vim commands for that. I will have to check whether the Vim session loading can be improved to show questions and messages.

**Comment by cometsong** [comment]
Everything's been updated in the last few years.... Open a new related one if this kind of this is *still* happening!
