### ISSUE TITLE
CtrlSpaceGoUp/Down mutually exclusive

### ISSUE THREAD

**Issue by Konfekt** [vim-ctrlspace/vim-ctrlspace#153]
The buffer list seems to be alphabetically ordered. This way, (because the omission of the absolute path in the current work dir changes the alphabetic order) `:CtrlSpaceGoUp` will never hit certain buffers (that `:...Down` hits though), and vice versa . The user supposedly expects  `:CtrlSpaceGoUp` to cycle through all buffers.

**Comment by szw** [comment]
Well, but it works in a cycle anyway... Have you tried that? ;)

**Comment by szw** [comment]
In other words, feel free to issue `:CtrlSpaceGoUp` and check. It would start from the bottom when it reach the top. It's an infinite cycle actually.

**Comment by Konfekt** [comment]
For example, 
```
b/b
z/a
z/c
```
Then `:CtrlSpaceGoDown` in `b/b` gives the cycle `z/a b/b z/a b/b ...`. Because if `z/a` is open then the alphabetic order is
```
a
b/b
c
```
and no longer
```
b/b
z/a
z/c
```

**Comment by szw** [comment]
Hmm... nope, I cannot confirm that. I tried your example: https://asciinema.org/a/6yjf208zrk4wpvy1k18dvvzoa and it behaves in a different way.

**Comment by Konfekt** [comment]
Hmm..  Over here, the paths in the buffer list are shortened relative to the cwd (that changes upon entering /z) . By the buffer list shown in the cinema, this does not happen in your case ?

**Comment by szw** [comment]
It depends on the current project root settings. If the z or b are also considered as a project root then together with `autochdir` set it seems possible.

**Comment by szw** [comment]
But `autochdir` always has been problematic for CtrlSpace. Similarly if you have project roots inside a project root that might be problematic too.

**Comment by Konfekt** [comment]
I guess the absolute path of b/b is /home/... 

Thus perhaps you can reproduce it with z/i instead of z/c? I am not sure if the Backslash in /home is considered though.

**Comment by Konfekt** [comment]
Yeah, but an autocmd that ses cwd= project root should go along with CtrlSpace. The shortening relative to the cwd is fine for display, but for sorting the full path should be used internally.

**Comment by szw** [comment]
The sorting part is a bit more complex. With the exception of tabs it uses the same algorithm to all other content. Some types of entries might have a full path (files), but some don't (bookmarks, unsaved buffers without files) etc. I would recommend to avoid `autochdir` or, even better, avoid nesting projects roots in other project roots.

**Comment by Konfekt** [comment]
How about sorting the buffers by their buffer number. Thus CtrlSpaceGoDown/Up mimics :bnext and :bprev for the current tab ? Most consistent and intuitive.

**Comment by szw** [comment]
Hmm... Ok, I will consider this as an config option but cannot make any promises :)

**Comment by Konfekt** [comment]
Instead, as more easily impleneted, an option to use the full path independent of the current work dir? (with ~ designing the hone dir for readability)

**Comment by cometsong** [comment]
Closing this issue, as #183 fixes it.
