### ISSUE TITLE
Tab key to open buffer window does not work

### ISSUE THREAD

**Issue by stephencheng** [vim-ctrlspace/vim-ctrlspace#154]
Hi firstly congrats on the hard work for release 5, I was happy using the old version for a couple of years already and finally hard to say good bye to previous version. Being spent a two days on it, it's really polished and well clearly structured. I find it difficult in the begining to grasp what key binding changes are but once got the idea, it's just like a " wow, that's it"

Report a key binding issue of the Tab key used for opening a buffer window, somehow it just does not work in my vim. I check through my vim config, it doesn't seem to be any conflict (not 100% confident though).  Suspecting these piece of code not handling the Tab key:

{{{
call ctrlspace#keys#AddMapping("ctrlspace#keys#tab#GoToTab", "Tab", ["Tab", "CR", "Space"])

function! ctrlspace#keys#tab#GoToTab(k)
    let nr = ctrlspace#window#SelectedIndex()
    call ctrlspace#window#Kill(0, 1)
    silent! exe "normal! " . nr . "gt"

```
if a:k ==# "CR"
    call ctrlspace#window#Toggle(0)
elseif a:k ==# "Space"
    call ctrlspace#window#Toggle(0)
    call ctrlspace#window#Kill(0, 0)
    call s:modes.Tab.Enable()
    call ctrlspace#window#Toggle(1)
endif
```

endfunction
}}}

see the if switch does not explicit handle the Tab. I short circuit to run:         call ctrlspace#window#Toggle(0) anyway, but the function is not triggered: ctrlspace#keys#tab#GoToTab

Hope I describe the problem clear

Thanks

**Comment by szw** [comment]
Thanks! I always love to see CtrlSpace works well for people :). Regarding the issue, the code you doesn't seem wrong to me:

```VimL
function! ctrlspace#keys#tab#GoToTab(k)
	let nr = ctrlspace#window#SelectedIndex() " Get the selected number and store it in variable nr
	call ctrlspace#window#Kill(0, 1) " Kill CtrlSpace window (close it
	silent! exe "normal! " . nr . "gt" " Go to the tab number stored in variable nr

        "Additionaly we can do some actions for CR and Space
	if a:k ==# "CR"
		call ctrlspace#window#Toggle(0)
	elseif a:k ==# "Space"
		call ctrlspace#window#Toggle(0)
		call ctrlspace#window#Kill(0, 0)
		call s:modes.Tab.Enable()
		call ctrlspace#window#Toggle(1)
	endif
endfunction
```

The general purpose of (or philosophy behind) the `Tab` key is to select (use) the item from plugin window and close the window immediately.

**Comment by stephencheng** [comment]
Thanks for explaining. However when I type Tab key, there is nothing happen: still stays on ctrlspace window and it does not open the buffer window, it works only when the cursor bar selected the current active buffer window.

Anyway I can help print out some debug information?

Also, is it possible ctrlspace#keys#tab#GoToTab not being called at all?

**Comment by cometsong** [comment]
Seems issue is dated or i'm unclear on it.  Please re-open if still having issue!
