### ISSUE TITLE
Problems with swp files

### ISSUE THREAD

**Issue by martin-hoger** [vim-ctrlspace/vim-ctrlspace#16]
Hi Szymon,

sometimes I used to experience that the Ctrl space didn't load my workspace and just hanged. I had to press ctrl+C, delete the workspace and create it again.
Today I have realized that the problem was caused by loading a "crached" file which had an existing swp file.

Not sure if this is something you can deal with, just wanted to let you know about the behaviour.

Best from Czech,

Martin

**Comment by bodograumann** [comment]
I have just started using ctrlspace (which is great btw.) and am now seeing this issue. Should I open a new report about it?

**Comment by cometsong** [comment]
@bodograumann - yes please open a new issue with a full description of the scenario and how we can reproduce it. :)
