### ISSUE TITLE
how close all other buffers in current tab

### ISSUE THREAD

**Issue by rlisowski** [vim-ctrlspace/vim-ctrlspace#166]
use case:
I have multiple tabs, each tab for project/task and one tab gets a lot open buffers after few days of development.

Is there any shortcut/function that allow delete/close all buffers but current one? I know there is [bufonly](https://github.com/schickling/vim-bufonly) but it closes all other buffers and I need close only other buffers in current tab.

Any idea how to do it?

**Comment by samuelsimoes** [comment]
I'd want know too.

**Comment by cometsong** [comment]
One issue with this is that any given buffer can be open in more than one tab.  so if you use `:bd` on it, all other `tab`s will have their versions dropped as well.  For my own working style, I would definitely prefer to "forget" them all from the current tab instead.  That's basically equivalent to creating a new tab with the current buf and then closing the previous tab.

**Comment by rlisowski** [comment]
For me, each tab represents different project so there is no way I have one buffer in more than one tab. I will give a shot the new tab approach. In the meantime, I'm testing tmux sessions so instead of many tabs I have vim with one tab in each tmux session.
