### ISSUE TITLE
Go directly to specific tab

### ISSUE THREAD

**Issue by mbrinkme** [vim-ctrlspace/vim-ctrlspace#170]
It's possible to go directly to the e.g. third tab?

In the last version from CtrlSpace I have the following mapping 

`nmap <leader>3 :w<cr>:CtrlSpace l<cr>3<cr>`

This was the perfect solution for me. But it doesn't work anymore! Can anybody help me?

**Comment by mbrinkme** [comment]
@szw Can you help me?

**Comment by Crisirf** [comment]
@mbrinkme 
How about this. 
 ** nmap <leader>3 :w<CR>:CtrlSpace l<CR>/3<CR>**
 but i think this is not a good way . Maybe the first match not your expected.

**Comment by Crisirf** [comment]
@mbrinkme Oh,my god , I'm sorry , something losed, 3 replace with /3

**Comment by cometsong** [comment]
Does this question mean you'd like a way to use a number within the Tab*L*ist to select that tab and show it's buffers? (Similar to selecting it by using `j/k` and pressing `<cr>` ?

A technique I often use to switch to the third tab is `3gt`, then `<c-_>` to see the list of files.
