### ISSUE TITLE
Fish shell compatibility

### ISSUE THREAD

**Issue by andersonba** [vim-ctrlspace/vim-ctrlspace#171]
Hi, first, thanks for this awesome plugin.

I got a error when I run `:CtrlSpace O` using fish, see:

![monosnap 2016-03-02 11-18-26](https://cloud.githubusercontent.com/assets/1501013/13462948/b44accc2-e068-11e5-885e-239071f25c48.jpg)

**Comment by Konfekt** [comment]
@andersonba Can you still reproduce this? I do not know where the `fish` variable could have been created.
