### ISSUE TITLE
ctrlspace#api#Tabline() needs to escape special characters

### ISSUE THREAD

**Issue by Konfekt** [vim-ctrlspace/vim-ctrlspace#176]
For example, opening a file `%.txt` shows `%.txtxt`.

**Comment by cometsong** [comment]
@Konfekt I just tried doing this by opening the CtrlSpace window, hitting `e` and then typing `%.txt<cr>`, which opens a file named `%.txt` ....  Do you want it to open some other file, e.g. `%` expanding to the current buffer name?

**Comment by Konfekt** [comment]
It happens when you open a file with a literal percent sign, for example `:e \%.txt`. Most probably some `fnameescape(..)` is missing.

**Comment by Konfekt** [comment]
This is solved in https://github.com/vim-ctrlspace/vim-ctrlspace/issues/176
