### ISSUE TITLE
Change up down keys?

### ISSUE THREAD

**Issue by pyros2097** [vim-ctrlspace/vim-ctrlspace#180]
Is it possible to change the up/down keys when navigating the file list?
`<h>, <j>` -> `<up>, <down>`?

And also I was trying to do something like visual studio code where I want to use `Ctrl-Tab` to cycle through my buffer list?

**Comment by ezmiller** [comment]
My up/down keys aren't working at all it seems. I would also be curious to know how these are set..

**Comment by spoike** [comment]
As explained in #193, according to the help file there is a `g:CtrlSpaceUseMouseAndArrowsInTerm` option. Set it to `1` to enable the up/down keys.

You should be able to do an `autocmd` (for `ctrlspace.txt` I believe) to bind [`<c-tab>` (only on gvim/macvim)](https://stackoverflow.com/questions/1646819/how-can-i-map-ctrl-tab-to-something-in-vim) with `:CtrlSpaceGoUp` and `:CtrlSpaceGoDown`
