### ISSUE TITLE
CtrlSpace breaks when path to file engine contains space

### ISSUE THREAD

**Issue by dalhorinek** [vim-ctrlspace/vim-ctrlspace#182]
I'm using nvim and macup to have my configs in icloud 

Since update to current version of vim ctrlspace now it throws an error when trying to open files 

`
Error detected while processing function ctrlspace#keys#Keypressed[14]..ctrlspace#keys#common#ToggleFileModeAndSearch[1]..<SNR>51_toggleListViewAndSearch[2]..ctrlspace#keys#commo
n#ToggleFileMode[5]..<SNR>51_toggleListView[18]..ctrlspace#window#Toggle[52]..ctrlspace#engine#Content[2]..<SNR>160_contentFromFileEngine:                                        
line    9:                                                                                                                                                                        
E15: Invalid expression: /bin/bash: /Users/dal/Library/Mobile: No such file or directory                                                                                          
E15: Invalid expression: /bin/bash: /Users/dal/Library/Mobile: No such file or directory                                                                                                                                                                             
`

`~/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.config/nvim/init.vim`

To fix it I used 
`
let fileEngine = substitute(s:config.FileEngine, '\s', '\\ ', '') 
`

inside `function! s:contentFromFileEngine()`

but there might be some better solution for this

**Comment by cometsong** [comment]
I can investigate this... can you make a PR for this issue?

**Comment by cometsong** [comment]
Fixed by @Konfekt with #209
