### ISSUE TITLE
ctrlspace at gvim8.0

### ISSUE THREAD

**Issue by bearmingo** [vim-ctrlspace/vim-ctrlspace#184]
I install gvim8.0 and ctrlspace in my Windows System. when open vim, pop a message "ctrlspace/context.vim runtime error at line 68"

**Comment by yehuohan** [comment]
adding 
```
set encoding=utf-8
```
to you vimrc may useful.

**Comment by thouqht** [comment]
@yehuohan this might be a good thing to have in the "Basic Setting" part of the readme? I had an error where all my symbols were screwed up and thought I was going to have to go in and remap every symbol.

**Comment by cometsong** [comment]
Good point on having this in the docs.
Right the doc only mentions UTF in the sections on [Symbols](https://github.com/vim-ctrlspace/vim-ctrlspace/blob/master/doc/ctrlspace.txt#L275)
