### ISSUE TITLE
how to avoid pressing `enter` twice to get into edit area, when i'm in the workspace list.

### ISSUE THREAD

**Issue by erictt** [vim-ctrlspace/vim-ctrlspace#186]
These are my procedures:
* open bookmarks with `b`, choose one to open
* press `w` to get the workspace list, then press `enter` to open one,
* it shows up all the buffered files, then I need to press `enter` again to switch to edit area.

My question is how to avoid pressing `enter` twice to get into edit area? What i want is when i get into the workspace, just jump into the last buffer. Is there any conf i can modify to suit my needs?

By the way, it is a great plugin, i finally can get rid of lots of plugins i don't like.

**Comment by TiuSh** [comment]
I found that in most cases you can use `tab` key instead of `enter` to automatically jump to the last used buffer in a workspace or tab. I think it should also work with your workflow.

**Comment by erictt** [comment]
@TiuSh Thanks. It is better than enter twice~~
