### ISSUE TITLE
Is this project still active ?

### ISSUE THREAD

**Issue by alexanderjeurissen** [vim-ctrlspace/vim-ctrlspace#187]
I recently discovered vim-ctrlspace, I really like the thought that has been put into optimising workflows etc. it's not just another fuzzy file finder.

I notice that the last commit of this project is almost a year old and I saw that you starred several emacs projects, Is it a safe assumption that you switched to Emacs and won't maintain this project anymore ?

If so have you found someone that is willing to commandeer this project ? Currently switching to this plugin seems like a risk as I'm not sure of it's stability and future improvement.

**Comment by alexanderjeurissen** [comment]
I've sent a message to the author of this plugin through the social media accounts of him that I could find on his website. Hopefully we can get clarity as of the status of this project soon.

**Comment by alexanderjeurissen** [comment]
I haven't heard back from the author of this plugin so I assume this project is dead.

**Comment by cometsong** [comment]
I'm currently maintaining a new fork of this plugin.

I've now merged in all merge-able pull requests from here and will continue to review/merge as time goes forward.

I'm too in love with this functionality to let it continue being deserted.  <3

**Comment by cometsong** [comment]
@alexanderjeurissen - Nvm on that last comment, I'm now up for maintaining and "keeping active" this plugin.  :)
