### ISSUE TITLE
Shortcut Ctrl-space not working in neovim

### ISSUE THREAD

**Issue by AdrianRibao** [vim-ctrlspace/vim-ctrlspace#188]
When Ctrl-space is pressed on neovim, it does nothing.

Here there is another issue that might be related and propose a solution, but it didn't work for me:

https://github.com/rogual/neovim-dot-app/issues/257

**Comment by dervos** [comment]
+1

**Comment by noidi** [comment]
You can use the following setting as a workaround:

    let g:CtrlSpaceDefaultMappingKey = "<C-space> "

Note the trailing space at the end of the mapping. Neovim doesn't mind it, but it makes vim-ctrlspace's "is the mapping left at default" check fail so it won't change the mapping to `<nul>` (as described in the issue linked above).

**Comment by AdrianRibao** [comment]
@noidi it works, thanks!
