### ISSUE TITLE
foldmethod is being applied to ctrlspace plugin window

### ISSUE THREAD

**Issue by bzub** [vim-ctrlspace/vim-ctrlspace#189]
If I `:set foldmethod=indent` the lists inside the ctrlspace plugin's window also get folded, so I only see a couple lines for files, buffers, etc.  I disabled everything in my vim setup except for vim-ctrlspace and the fold setting to figure this out.

**Comment by cometsong** [comment]
Still having this `foldmethod` issue?

**Comment by cometsong** [comment]
Fixed, using `setlocal foldmethod=manual` in pull request from @octobanana
