### ISSUE TITLE
Fuzzy search ignore folder?

### ISSUE THREAD

**Issue by brandonsturgeon** [vim-ctrlspace/vim-ctrlspace#190]
So far this seems like a great tool, but the fuzzy search is getting really really slow because it's indexing my `node_modules/` folder, which has tons and tons of files.

I don't even want it to include that folder at all. Could I get a `.ctrlspacerc` or something where I can ignore folders?

**Comment by brandonsturgeon** [comment]
@szw Is this project no longer maintained?

**Comment by yourpalal** [comment]
If you use `ag` it will ignore paths from your `.gitignore` . It also has its [own similar file called .agignore](https://stackoverflow.com/questions/22999346/silver-searcher-how-to-ignore-a-file#29740677)

**Comment by brandonsturgeon** [comment]
Yeah, that's the solution I've been using. It actually seems like a better solution than having this functionality in ctrl-space.

**Comment by brandonsturgeon** [comment]
So, I was just using a hacky custom vim command for fuzzy searching with `ag`. I want to use ctrlspace's fuzzy search, but I want it to use `ag`

I've put the following code in my `.vimrc`
```
if executable("ag")
    let g:CtrlSpaceGlobCommand = 'ag -l --nocolor -g ""'
endif
```

(Silver searcher is definitely installed)

Fuzzy search still shows everything from folders which should be excluded in both `.gitignore` and `.agignore`

**Comment by brandonsturgeon** [comment]
I was being stupid I'm sorry! 😣 

I just had to use the <o> and <r> command to refresh everything, and it's working now!

**Comment by adithyaov** [comment]
@brandonsturgeon Not stupid, Just stated using ctrlspace and your comment was helpful!
