### ISSUE TITLE
Errors on powershell (windows)

### ISSUE THREAD

**Issue by sahilsk** [vim-ctrlspace/vim-ctrlspace#192]
Error messages on vim startup

Error
```
find: `Program Files(x86)': No such file or directory
The process tried to write to a nonexistent pipe.
The process tried to write to a nonexiste....
```
It turn out fileEngine detection logic is breaking on `powershell` , though it works fine on `cmd prompt`

```
»···if has("win32")                                                                       
»···»···let os   = "windows"                                                              
»···»···let arch = empty(system('set | find "ProgramFiles(x86)"')) ? "386" : "amd64"     
»···else                                                                                  
»···»···let uname = system("uname -a")                                                    
```

So,  `set | find "ProgramFiles(x86)"`  doesn't work on powershell

```
»···»···let arch = empty(system('set | find "ProgramFiles(x86)"')) ? "386" : "amd64"     
```

Any help here would be great.

**Comment by sahilsk** [comment]
I tried replacing `set` by `env` and it did help. 
Now the second issue came with `find` command which is not in powershell.

I tried sls/select-string , surprisingly it says 
`
'select-string' is not recognized as an internal or external command,
```

**Comment by cometsong** [comment]
This is not something I can test directly (no access to a windows box I can fiddle with) but definitely sounds like a bug for the powershell setup.  I suggest asking another user to also test this setup and then making a PR for it.  Sounds like a simple fix in your description, but want to make sure it doesn't also change other usage 'arch's. 👍

**Comment by Konfekt** [comment]
One could think about replacing the check of existence of the folder `ProgramFiles(x86)` by simply `has('win32') && !has('win64')`.
