### ISSUE TITLE
Up/down keys not working in neovim

### ISSUE THREAD

**Issue by ezmiller** [vim-ctrlspace/vim-ctrlspace#193]
I'm unable to use the up/down keys to navigate in the ctrlspace view. Has anyone else experienced this? I'm using neovim.

**Comment by spoike** [comment]
up/down keys aren't mapped, only j/k keys are.

**Comment by ezmiller** [comment]
Thanks for the clarification.

**Comment by spoike** [comment]
According to the help file there is a `g:CtrlSpaceUseMouseAndArrowsInTerm` option.

```
let g:CtrlSpaceUseMouseAndArrowsInTerm = 1
```

in your .vimrc should enable these keys.
