### ISSUE TITLE
How to switch workspace?

### ISSUE THREAD

**Issue by yehuohan** [vim-ctrlspace/vim-ctrlspace#195]
How to switch workspace to another?
Or How to show all workspace in workspace-list?

**Comment by fiendzhu** [comment]
> How to switch workspace to another?
> Or How to show all workspace in workspace-list?

Have U solved the problem? I'm facing the same question..Don't know how to make it worked.

**Comment by yehuohan** [comment]
@fiendzhu
I find nothing command to do that.
Maybe you can use my fork:

https://github.com/yehuohan/vim-ctrlspace

Or  popc, which is more flexible:

https://github.com/yehuohan/popc
