### ISSUE TITLE
Weird insertion of "qq" when using hjkl-keys to move.

### ISSUE THREAD

**Issue by bpfel** [vim-ctrlspace/vim-ctrlspace#199]
I am using ctrl-space on arch-linux within neovim and currently have a problem with these "qq" appearing whenever I try using the ctrl-space environment. Does anybody know the issue?

![image](https://user-images.githubusercontent.com/28698417/35093065-8bc839fa-fc41-11e7-9922-8c96c85b4a9b.png)

![image](https://user-images.githubusercontent.com/28698417/35093009-52b842c2-fc41-11e7-8aa0-308d0aa1e410.png)

**Comment by cometsong** [comment]
I can't reproduce this behaviour using neovim on either CentOS or MacOS.
Possibly a different `vimrc` config issue?

**Comment by bpfel** [comment]
@cometsong Yeah, I cannot reproduce it on Manjaro either. It only happens when I'm on arch-linux.
