### ISSUE TITLE
on entering vim load all files in initial tab page

### ISSUE THREAD

**Issue by Konfekt** [vim-ctrlspace/vim-ctrlspace#204]
When starting Vim to edit multiple files,  say by `vim a.txt b.txt`, how to achieve that both files `a.txt` and `b.txt` are listed in the buffer list of the current initial tab page?

Currently, only `a.txt` is listed, but `b.txt` not.

**Comment by cometsong** [comment]
Using CtrlSpace buffer list, it by default shows only the *current* tab's buffers; you can then hit the key `a` (*for 'all'*) and it will list all buffers, just as using vim's standard command `ls`. 
(N.B.: To list *every* buffer including 'unlisted' and 'hidden' you can use `ls!`.)

If vim is opened "normally" (i.e. the default without any command line options or vimrc mods) - then it would open both files in the same "tab" and you would switch between with `buffer 2` or buffer-next using `bnext`.

Do you have vim setup to automatically separate files into two tabs (or one per each file)?  Equivalent to using `vim -p a.txt b.txt`?

**Comment by cometsong** [comment]
*(Just realized you know this plugin well and have committed to it!  Doh!)*

That vim-opening kinda why I asked about this, as my vim session always starts with all the files in a single tab, thus having CtrlSpace open all the files together.

Just now I tested with *new* files that have no data in them, and I see it doesn't show the others that have not been editied (created) yet.  Not sure if that's a vim issue or this plugin, as vim itself will not write the `unmodified` files unless told to explicitly e.g. using `:wa!`.  

The `:ball` command also does not put them in the CtrlSpace buffer list, despite vim opening each in its own window within the current tab.  Hmmm.  That will need some further investigation on the method CtrlSpace uses to get the buffer list.

**Comment by Konfekt** [comment]
Thanks for investigating this.

> That vim-opening kinda why I asked about this, as my vim session always starts with all the files in a single tab, thus having CtrlSpace open all the files together.

Not sure what this means. If CtrlSpace opens all files together, does it mean that they all show up in the buffer list of the single tab page? That's not happening here, even for pre-existent files. Is there a special command in your `vimrc` to achieve this?

> The :ball command also does not put them in the CtrlSpace buffer list, despite vim opening each in its own window within the current tab. Hmmm. That will need some further investigation on the method CtrlSpace uses to get the buffer list.

True, only after having switched windows, all buffers show up.

**Comment by Konfekt** [comment]
This was adddressed by https://github.com/vim-ctrlspace/vim-ctrlspace/pull/220#issuecomment-503731466
