### ISSUE TITLE
Debugging the slow load time

### ISSUE THREAD

**Issue by justrajdeep** [vim-ctrlspace/vim-ctrlspace#205]
6106.452  5042.388  5042.388: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/context.vim
    6107.989  000.388  000.388: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/modes.vim
    6108.046  5045.213  002.437: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/init.vim
    6109.394  000.132  000.132: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys.vim
    6110.736  000.124  000.124: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/roots.vim
    6112.190  000.175  000.175: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/bookmarks.vim
    6115.680  000.262  000.262: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/common.vim
    6117.519  000.331  000.331: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/help.vim
    6118.956  000.134  000.134: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/help.vim
    6121.050  000.053  000.053: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/nop.vim
    6122.876  000.078  000.078: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/search.vim
    6124.748  000.230  000.230: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/buffer.vim
    6127.300  000.110  000.110: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/file.vim
    6129.316  000.113  000.113: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/tab.vim
    6131.052  000.109  000.109: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/workspace.vim
    6132.458  000.071  000.071: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/bookmark.vim
    6132.783  5071.145  024.010: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/plugin/ctrlspace.vim

I am using `Red Hat Enterprise Linux Client 6 U7` on an `x86_64` box with `8` cores and `32 GB` ram.
I am trying to see why the plugin load is slow, I just see one `system` call in 

    /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/context.vim

**Comment by justrajdeep** [comment]
With `let CtrlSpaceFileEngine = 'file_engine_linux_386'` this is what i am getting

    1460.822  001.236  001.236: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/context.vim
    1462.557  000.358  000.358: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/modes.vim
    1462.631  005.019  003.425: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/init.vim
    1464.406  000.177  000.177: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys.vim
    1466.129  000.177  000.177: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/roots.vim
    1467.804  000.197  000.197: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/bookmarks.vim
    1473.044  000.361  000.361: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/common.vim
    1475.723  000.519  000.519: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/help.vim
    1477.503  000.164  000.164: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/help.vim
    1480.173  000.077  000.077: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/nop.vim
    1482.847  000.083  000.083: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/search.vim
    1485.652  000.379  000.379: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/buffer.vim
    1489.700  000.176  000.176: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/file.vim
    1492.125  000.209  000.209: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/tab.vim
    1494.604  000.148  000.148: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/workspace.vim
    1496.430  000.088  000.088: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/bookmark.vim
    1496.758  041.406  033.632: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/plugin/ctrlspace.vim
    1812.529  013.371: opening buffers
    1814.626  000.333  000.333: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/buffers.vim
    1816.336  000.108  000.108: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/jumps.vim

**Comment by cometsong** [comment]
The timing of skipping that chunk of the `context.vim` logic (determining the ) looks drastically faster; 0.025% of the previous context time you showed.

Looking again at the `context` source, the file engine it will choose ([detectEngine](autoload/ctrlspace/context.vim#L107) will be `'file_engine_linux_amd64'` as you have `x86_64` in the `uname -a` from your machine.

So the next step is trying to set the file engine variable to that name and see if the system call in the context file takes just as long as it did previously.

**Comment by justrajdeep** [comment]
Sorry for the delay

Setting `let CtrlSpaceFileEngine = 'file_engine_linux_amd64'` speeds up things.

    times in msec
     clock   self+sourced   self:  sourced script
     clock   elapsed:              other lines
    
    000.004  000.004: --- VIM STARTING ---
    000.110  000.106: Allocated generic buffers
    001.457  001.347: locale set
    001.477  000.020: GUI prepared
    001.479  000.002: clipboard setup
    001.489  000.010: window checked
    001.835  000.346: inits 1
    001.860  000.025: parsing arguments
    001.862  000.002: expanding arguments
    001.881  000.019: shell init
    002.188  000.307: Termcap init
    002.228  000.040: inits 2
    002.343  000.115: init highlight
    1381.691  001.214  001.214: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/context.vim
    1383.485  000.244  000.244: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/modes.vim
    1383.539  004.462  003.004: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/init.vim
    1385.416  000.126  000.126: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys.vim
    1387.005  000.129  000.129: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/roots.vim
    1388.826  000.146  000.146: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/bookmarks.vim
    1393.251  000.293  000.293: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/common.vim
    1396.060  000.363  000.363: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/help.vim
    1397.878  000.177  000.177: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/help.vim
    1400.723  000.079  000.079: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/nop.vim
    1403.032  000.076  000.076: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/search.vim
    1405.479  000.237  000.237: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/buffer.vim
    1408.653  000.119  000.119: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/file.vim
    1411.381  000.134  000.134: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/tab.vim
    1413.753  000.105  000.105: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/workspace.vim
    1415.599  000.074  000.074: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/keys/bookmark.vim
    1415.930  038.742  032.222: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/plugin/ctrlspace.vim
    1673.088  014.996: opening buffers
    1675.728  000.292  000.292: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/buffers.vim
    1677.569  000.094  000.094: sourcing /home/ramondal/.vim/neobundle_bundle/ctrlspace/autoload/ctrlspace/jumps.vim
    1677.619  004.145: BufEnter autocommands
    1677.624  000.005: editing files in windows
    1729.604  001.953: first screen update
    1729.605  000.001: --- VIM STARTED ---

**Comment by cometsong** [comment]
That’s great to see!
This speed work for you?

**Comment by justrajdeep** [comment]
Yes this is fine.

Closing this issue.
