### ISSUE TITLE
Search mode doesn't trigger occasionally

### ISSUE THREAD

**Issue by TyOverby** [vim-ctrlspace/vim-ctrlspace#207]
Sometimes when I hit `/` for search in the buffers list, nothing happens and pressing subsequent keys gives me the message 

`E21: Cannot make changes, 'modifiable' is off.`

**Comment by TyOverby** [comment]
After looking closely, it appears that *something does happen* when I press `/`: it goes into what looks like insert mode inside of the ctrl-space buffer.

**Comment by cometsong** [comment]
Does that discovery close this issue?  Or is it also still giving your the `modifiable` error msg?  This doesn't happen on my end at all, so I'm curious if your config sets this??

I get this type behaviour when I open the `CtrlSpace` window and hit `/`, then (here) type "Name":
![image](https://user-images.githubusercontent.com/307777/50600829-608d8180-0e80-11e9-9384-f90fa35e6a0b.png)

**Comment by TyOverby** [comment]
Yes, I think I discovered that it was a conflict with another plugin.
