### ISSUE TITLE
Cannot spawn CtrlSpace window via keymapping

### ISSUE THREAD

**Issue by mistermaps** [vim-ctrlspace/vim-ctrlspace#213]
Hi there.

This is an incredibly useful plugin for my purposes but I've been having some trouble with it.

The <c-space> mapping was conflicting with another plugin (vimwiki.) After some searching, I realized that said other plugin's mapping was a function I never used and likely never would, so I disabled it by commenting out the offending code in the plugin.

This removed the conflicting mapping. However, hitting <C-Space> still did bring up CtrlSpace.

Current mapping is:
`n  <C-Space>   * :CtrlSpace<CR>                                             
        Last set from ~/.vim/plugged/vim-ctrlspace/autoload/ctrlspace/keys.v
im line 159   `

As an attempt as a workaround, I have also tried several hacked solutions, placing the following in my .vimrc:
`let g:CtrlSpaceDefaultMappingKey = "<C-space> "`
`noremap <M-space> "CtrlSpace<CR>"`
`autocmd VimEnter * noremap <C-Space> CtrlSpace<CR>`
`autocmd VimEnter * noremap <M-Space> CtrlSpace<CR>`

I have also tried the above by alternating Ctrl and Meta in the first two lines (i.e, mapping DefaultMappingKey to <M-space>, or noremapping <C-Space> to CtrlSpace + carriage return.

None of these bring up CtrlSpace, whereas 
`:CtrlSpace`
works fine.

I'm not entirely sure what's going on here or if I'm doing anything wrong, since I cannot find any conflicts, and
`:verbose map <C-space>`
+ M-space both return 'CtrlSpace<CR>'.

Please let me know if you have any suggestions as to what may be causing the error or if you have ideas for how to rectify this issue on my end.

Thanks!

**Comment by cometsong** [comment]
*(Sorry for late reply)*

Was looking through the keymapping's you've tried; came up with one other option - try adding in `:`
```
noremap <C-Space> :CtrlSpace<CR>
noremap <M-Space> :CtrlSpace<CR>
```

That way the mapping knows to enter the text on the command line.

**Comment by cometsong** [comment]
Plus, please tell me what version of (neo)vim you're using, to help me put that kind of test into the app-wide test-suite i'm currently creating.  Thanks!

**Comment by cometsong** [comment]
Closing because no response from issuer.
