### ISSUE TITLE
Faster navigation between buffers when the intention is to skim through different files?

### ISSUE THREAD

**Issue by shaform** [vim-ctrlspace/vim-ctrlspace#215]
Hi,

I often have to quickly switch through all buffers to inspect the file contents quickly.
It's quite slow to do the following:

1. open buffer list
2. select next buffer
3. open the buffer
4. goes to 1

Is it possible to have a mode where you would:

1. open buffer list
2. select next buffer
3. the buffer is automatically loaded into the window, and the buffer list is not closed, so you could continue to select the next buffer
4. goes to 2

Thanks!

**Comment by cometsong** [comment]
Yep, this can easily be done by selecting the buffer in the list and then pressing capital letters: 
- `S` to open in split window, 
- `V` to open in vertical, 
- `T` to open in new tab, 
- or `Space` to open in current window 
(whichever one you were in when you activated `CtrlSpace`).  

The capital letters keep the focus on the `CtrlSpace` window; whereas the lowercase (`s`, `v`, `t`, or `<cr>`) open the buffer and focus on the window/tab it opens in.

So you do: 
1. open buffer list
2. select a buffer
3. type `S`, `V`, `T`, or `space`
4. "inspect file contents quickly" :)
5. `J` to go next buffer in list, then go to "3"

Make sense?

**Comment by cometsong** [comment]
By the way, when you open the `CtrlSpace` window, you can hit the `?` button to toggle a local "Help" window inside it, which lists all the possible keys available in that specific mode (e.g. buffer list or tab list).

**Comment by shaform** [comment]
Thanks for the explanation!
