### ISSUE TITLE
Feature request: make `:bd` not to delete the tab if more buffers exist

### ISSUE THREAD

**Issue by randomizedthinking** [vim-ctrlspace/vim-ctrlspace#218]
I am experimenting with ctrlspace for my workflow. There are many good stuffs I like. Yet, one item bothers me is when I delete some buffers. Since ctrlspace uses vim tab to organize buffers, when the user deletes a buffer using command `:bd`, the tab is also deleted. It thus destroys the layout I carefully created.

I would like to request a new feature that: when a user deletes a buffer, if there are more buffers in the tab, then ctrlspace simply moves to next buffer rather than delete the tab.

**Comment by randomizedthinking** [comment]
Not sure it is doable in vim since we have to intercept `:bd` command. I know I need to use `<C-Space>d`, yet my fingers always press `:bd` without my noticing it.

**Comment by cometsong** [comment]
I think CtrlSpace's main method is the `d` (or `c`) within it's window.
On the vim side, I use another technique for this, which is a mapping to a plugin (currently using [Sayonara](https://github.com/mhinz/vim-sayonara) thought) for `bd` to equal "delete buffer and replace it with latest-used buffer" instead of closing the window itself, or to a blank buffer if no other active ones.

**Comment by randomizedthinking** [comment]
Can CtrlSpace implement a similar command as in `Sayanara`, like `:Bd`, which delete a buffer and switch to another buffer in the tab if there is any?

**Comment by Konfekt** [comment]
There are already those commands. These are my mappings to close the buffer, keeping respectively closing its tab page:
```vim
nnoremap <silent> Q          :<c-u>CtrlSpace cq<CR>
nnoremap <silent> gQ       :<c-u>CtrlSpace xcq<CR>
```
Without Ctrl-Space, there are the fallbacks
```vim
nnoremap <buffer><silent><nowait>  Q  :<c-u>Bdelete<CR>
nnoremap <buffer><silent><nowait> gQ  :<c-u>bdelete<CR>
```
where 
```vim
command! -bang Bdelete call s:bdelete(expand("<bang>"))
function! s:bdelete(bang)
  let curbufnr = bufnr("%")
  let altbufnr = bufnr("#")

  if buflisted(altbufnr)
    buffer #
  elseif len(filter(range(1, bufnr('$')), '! empty(bufname(v:val)) && buflisted(v:val)')) > 1
    bnext
  endif

  if bufnr("%") == curbufnr
    enew
  endif

  if buflisted(curbufnr)
    execute("bdelete". a:bang. " " . curbufnr)
  endif
endfunction
```

**Comment by cometsong** [comment]
@randomizedthinking - Does this work for you?  Is this *closable*?

**Comment by randomizedthinking** [comment]
Yes, it works nicely and we can close it now... thanks! Some minor modifications: I define the command as `:Bd` instead, and use `cabbrev` to convert `:bd` to `:Bd` -- so my fat finger won't cause any trouble.

```vim
command! -bang Bd call s:bdelete(expand("<bang>"))
cabbrev bd Bd
```
