### ISSUE TITLE
Mappings conflicts

### ISSUE THREAD

**Issue by jmolero** [vim-ctrlspace/vim-ctrlspace#221]
Hi, thanks for making this plugin!

I have a problem with some of the mappings. When I type a key like d it doesn't delete a buffer right away. I have to type another key like enter to make it work. 

I found that's because I have the notimeout option set and some other mappings also start with the same key. I have more than one of these 'conflicts' with different keys.

Wouldn't be possible to only allow CtrlSpace mappings inside a list? I don't think other mappings are needed inside a list.

**Comment by cometsong** [comment]
Can you give examples of the conflicting mappings you mentioned?
How are they declared? IN your `vimrc`? In an `after` file? Somewhere else?

**Comment by jmolero** [comment]
The conflict with the `d` command I was mentioning comes from `vim-surround`:

ds    <Plug>Dsurround    vim-surround/plugin/surround.vim

If I disable that plugin, the `d` command deletes the buffer as expected.

**Comment by cometsong** [comment]
Yep, I just now set the `notimeout` option and that's the clincher.  

I also use (and love)`vim-surround` and have no problem at all with the two mappings without `notimeout`.  The `d` and `ds` keymaps work fine.
So... why `notimeout`? Just a preference for other uses?

If you *do* want to keep that setting, you can use `dd` as an in-app version of `bd!` (which is the eventual final command after the re-setup of all the buffer and tablists within the C-Space app).  That second `d` becomes the next requisite key pressed.

(As a mnemonic, delete the line with that buffer in it.)

**Comment by jmolero** [comment]
Thanks for trying it out.

What I like about having `notimeout` enabled is that it waits until I type a full mapping, but I found a better workaround for me based on your setting.

I disabled `notimeout` and set `timeoutlen=30000`. That way C-Space commands work immediately and I still can have that wait for full mappings to be entered.
