### ISSUE TITLE
remove rarely used binaries in ./vim-ctrlspace/bin/

### ISSUE THREAD

**Issue by Konfekt** [vim-ctrlspace/vim-ctrlspace#225]
Because this plug-in takes up around 130 MB by the binaries in vim-ctrlspace/bin/ for every architecture, and a Vim configuration is, arguably, meant to be carried around, one could think about keeping only the executables for the most common architectures Darwin, Linux and Windows for 64 bit, and make the others available elsewhere, for example, in a downloadable release.

**Comment by cometsong** [comment]
Agree on smaller size.
We'll need to make other OS versions relatively-quickly attainable, as you said.
Is there a github-method to make downloadable releases only of certain files? 
I know for example `pip` can take specific args for sub-module styles. 
Maybe a separate file_engine_download branch?  To be updated with any changes to the code (e.g. re-compile with latest version of `go`).

**Comment by Konfekt** [comment]
Putting the rarely used engines into a separate branch is a first step. More thorough would be to tag a release and upload them at https://github.com/vim-ctrlspace/vim-ctrlspace/releases/new .
