### ISSUE TITLE
Can not reload file list when no files match

### ISSUE THREAD

**Issue by bodograumann** [vim-ctrlspace/vim-ctrlspace#226]
**Describe the bug**
When the filter in the file view does not return any results its not possible to refresh the file list cache with `r`.

**To Reproduce**
1. Open the panel with Ctrl+Space
2. Press 'O' to search for files
3. Search for a file which is not in the cached list of files
4. Press `r` in order to reload the file list cache
5. See error:
    > ⌗  Key 'r' doesn't work in this view.

**Expected behavior**
The file list cache should be refreshed and the filter should then show the file that was searched.

**Version:**
 - OS: Gentoo linux
 - Version
    > VIM - Vi IMproved 8.1 (2018 May 18, compiled May 26 2019 18:26:26)                                                                                                                           
    > Included patches: 1-648
    > Modified by Gentoo-8.1.0648-r1

**Additional context**
As long as the filter returns some result, pressing `r` works fine. Only after no more files match, the error occurs.

**Comment by jyscao** [comment]
@bodograumann hey man, I submitted a PR fixing this issue in #245. Please take a look, and test it out if you like. Feedback is very much welcome.
