### ISSUE TITLE
Save folds with the workspace

### ISSUE THREAD

**Issue by jmolero** [vim-ctrlspace/vim-ctrlspace#227]
Would it be possible to save folds along with the workspace? 

I'd like to have them restored when opening vim again?

I think vim sessions can do that.

 - OS: osx mojave
 - Version:  nvim v0.3.7

**Comment by Konfekt** [comment]
This could be achieved by https://github.com/zhimsel/vim-stay.

**Comment by jmolero** [comment]
Thanks @Konfekt I didn't know about vim-stay. 

I tried it and it restores the folds at startup but only if I disable vim-ctrlspace. Maybe I'm missing some configuration. I did read the vim-stay docs and used the recommended settings.

**Comment by Konfekt** [comment]
Try `set sessionoptions+=folds`.

**Comment by jmolero** [comment]
I tried but I was already set anyway and doesn't work. It does recover the folds if I disable ctrlspace.

**Comment by Konfekt** [comment]
Perhaps `set sessionoption-=folds` will work, either using `vim-stay` or not?

**Comment by jmolero** [comment]
sessionsoptions doesn't seem to make any differenced. And I  need vim-stay to have the folds restored.  But it only works if I comment out the vim-plug line for ctrlspace.

**Comment by Konfekt** [comment]
But loading a session by `:mksession` with `sessionsoptions+=folds` does restore folds? Looking at `.git/cs_workspaces`, it does not save folds, but then again, because of `vim-stay`, they are restored anyway. Perhaps it is because I use in conjuntion my FastFold plug-in?

**Comment by jmolero** [comment]
Loading a session saved with `:mksession` does restore the folds. `sessionoptions` includes folds. I tried vim-stay in conjunction with FastFold but doesn't restore the folds automatically either.

**Comment by Konfekt** [comment]
Please add to your `vimrc`
```
autocmd SessionLoadPost * stay#view#load(stay#win#getid(winnr()))
```
Perhaps one needs to submit an integration module for vim-stay as documented in `:help vim-stay-integration`.
Have you looked into that?

**Comment by jmolero** [comment]
I tried adding that autocmd but I get this error: 
```
Error detected while processing SessionLoadPost Autocommands for "*":
E492: Not an editor command: stay#view#load(stay#win#getid(winnr()))
```
I looked at the integration docs and the FastFold integration but I don't understand how to add one, sorry.

**Comment by Konfekt** [comment]
I beg your pardon, it is
```vim
autocmd SessionLoadPost * call stay#view#load(stay#win#getid(winnr()))
```

**Comment by jmolero** [comment]
No problem. Thanks for taking the time to help me with this.

This autocmd doesn't give me an error on start but still no luck on restoring the folds. 

It's strange. This autocmd doesn't seem to be needed if disabling ctrlspace, folds are restored if disabled.

**Comment by Konfekt** [comment]
If you call it manually after loading a CtrlSpace session, does it restore folds corectly?

**Comment by Konfekt** [comment]
Just to be sure, `folds` figure in your viewoptions.

**Comment by Konfekt** [comment]
Is any of this different under Vim instead of NeoVim?

**Comment by jmolero** [comment]
These are my settings: `viewoptions=cursor,folds,slash,unix`

I get the same results with vim as with neovim.

**Comment by Konfekt** [comment]
If you call `call stay#view#load(stay#win#getid(winnr()))` manually after loading a CtrlSpace session, does it restore folds correctly?

**Comment by jmolero** [comment]
No, it doesn't. I still think that is something conflicting with the ctrlspace session, vim-stay works without it.

**Comment by Konfekt** [comment]
What does `call stay#view#load(stay#win#getid(winnr()))` do? Nothing. Is there a view file? If yes, what does it contain? What does `call stay#view#make(stay#win#getid(winnr()))` return? Does ``call stay#view#load(stay#win#getid(winnr()))` work after `...make(...)` has been called manually?

**Comment by jmolero** [comment]
There's no error message after calling `call stay#view#load(stay#win#getid(winnr()))`. The only change is the cursor position, it goes to the beginning of the buffer. 

I had to check where the views are located. They are at: `~/.local/share/nvim/view`
I'm testing the folds on my vimrc file. The name for its view file is: `~=+Development=+Tools=+Neovim=+vimrc=`.

And it contains this:
```
let s:so_save = &so | let s:siso_save = &siso | set so=0 siso=0
argglobal
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
silent! normal! zE
let s:l = 1 - ((0 * winheight(0) + 14) / 29)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
1
normal! 0
let &so = s:so_save | let &siso = s:siso_save
doautoall SessionLoadPost
" vim: set ft=vim :
```
When I tried to load the file with: `:loadview ~/.local/share/nvim/view/~=+Development=+Tools=+Neovim=+vimrc`
I got the following error:  `E484: Can't open file /Users/jorge/.vimviews//~=+Development=+Tools=+Neovim=+vim=+settings.vim=/.vim`

I'm not sure if that's the way `loadview` should be used. 
Then I tried changing the views location with `viewdir` to see if there was a problem reading the files there, but no luck. The files are created in the new location but can't still be read by calling `loadview`, although vim-stays seems to have no problems writing them in either location.

**Comment by Konfekt** [comment]
The file is loaded by `:source path` instead of `:loadview path`. Instead `:loadview` sources a view of the current file. Looking at the view file, nothing is folded and the foldmethod is `manual`. Is that as it should be? 

If there are open folds, then in it there are commands such as
```
11
normal! zo
29
normal! zo
```

**Comment by jmolero** [comment]
Thank for your reply. 
I'm not sure if the foldmethod should be manual. I've seen the other options and I would say it is ok for me as long as no other setting is required for this to work.

I checked the file after adding a fold. I can see it added this: `14,22fold`. Sourcing that file does restore the fold. But when ctrl-space is enabled this fold info `14,22fold` is removed at startup. If I disable ctrl-space by commenting it out in my vimrc the fold info is kept in the view file after a restart and the folds are applied.

**Comment by Konfekt** [comment]
At https://github.com/vim-ctrlspace/vim-ctrlspace/blob/32430cd01760f761669442415335b0200632a2ae/autoload/ctrlspace/workspaces.vim#L388 everything but buffer and tab opening commands are filtered out. Perhaps for good reason by the original author? 

If folds have to be preserved, then lines such as `[RANGE]fold` have to be permitted as well.

**Comment by Konfekt** [comment]
This is, CtrlSpace sessions are completety unrelated to &sessionoptions and &viewoptions. 

It is not clear to me why a list commands that load buffers destroys all folds loaded afterwards by `vim-stay`. Only a minimal `vimrc` could tell.

**Comment by Konfekt** [comment]
It also is not clear to me why the explicte `doautoall SessionLoadPost` has no effect in your setup. 

Please provide a reproducible minimal `vimrc` to understand what's happening before further discussion.

**Comment by Konfekt** [comment]
Looking at 
```vim
" autoload/ctrlspace/workspaces.vim (line 388)
for cmd in readfile("CS_SESSION")
```
there is seeminlgy nothing that removes the fold commands.

**Comment by jmolero** [comment]
Thanks. I think I found it. It happens if I use this setting `let g:CtrlSpaceLoadLastWorkspaceOnStart = 1`. If set to zero it works as expected. 

This is the smallest vimrc file I could get that reproduces it and includes my settings:

```
" Plugins
filetype plugin on
call plug#begin('~/.vim/plugged')

Plug 'vim-ctrlspace/vim-ctrlspace'
Plug 'zhimsel/vim-stay'

call plug#end()

set hidden

let g:CtrlSpaceLoadLastWorkspaceOnStart = 1
let g:CtrlSpaceSaveWorkspaceOnSwitch = 1
let g:CtrlSpaceSaveWorkspaceOnExit = 1
let g:CtrlSpaceGlobCommad = 'rg -l --nocolor -g ""'
```

**Comment by jmolero** [comment]
I checked again after a while and it seems to be fixed now. The folds are kept on a restart.

**Comment by Konfekt** [comment]
That's good news, and thus the issue can be closed?

**Comment by jmolero** [comment]
Yes. Thank you for your help!

**Comment by Konfekt** [comment]
@jmolero, 
There is the line

```vim
" autoload/ctrlspace/workspaces.vim (line 347)
set ssop=winsize,tabpages,buffers,sesdir
```

that disables saving the folds in `&sessionoptions`.

You could test enabling saving them by adding the line `set ssop+=folds` or use [vim-stay](https://github.com/zhimsel/vim-stay).

Please try adding `set ssop+=folds` as mentioned above to force `vim-ctrlspace` to save folds (I supposed that your `&ssop` included `folds`).

By the way, I am using vim-stay with vim-ctrlspace and folds are restored fine. Perhaps you could provide a minimal `vimrc` to sort this out?

**Comment by jmolero** [comment]
Adding `set ssop+=folds` solved the problem. I also have `vim-stay` installed. I strange that it doesn't work in my case . 

After installing `vim-stay` I added this to my vimrc `set viewoptions=cursor,folds,slash,unix`, and my `ssop` include folds too.

Thanks for the help.

**Comment by Konfekt** [comment]
Ah, then your `&ssop` probably don't include `folds`. Check your `vimrc`.

To be sure, you added `ssop+=folds` after the line

```vim
" autoload/ctrlspace/workspaces.vim (line 347)
set ssop=winsize,tabpages,buffers,sesdir
```

or in your `vimrc`?

**Comment by jmolero** [comment]
Yes, I added the line to ctrlspace after 347. What I find strange is that `ssop` is never set in my `vimrc`, but it does include `folds` if I execute `set ssop?`: 

```
sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize
```

**Comment by Konfekt** [comment]
Yes, it is the default option, see `:help ssop`.

One could think about respecting the user's session options, or make CtrlSpace's options customizable.

**Comment by TangMonk** [comment]
Why not make auto save fold as a default behavior for CtrlSpace

**Comment by Konfekt** [comment]
Too intrusive if there is `sessionoptions=folds` to be respected and [vim-stay](https://github.com/zhimsel/vim-stay).

**Comment by 3ddiddE** [comment]
So, is it correct that I need vim-stay or manual mkview/loadview to store/restore folds?
Maybe someone could add this information to the readme?

**Comment by Konfekt** [comment]
Yes, that's correct. @jyscao please correct me otherwise. Would you, @3ddiddE, mind a pull request?

**Comment by 3ddiddE** [comment]
@Konfekt I will try to look into it on the weekend!

**Comment by Konfekt** [comment]
@3ddiddE : I looked into it:

In

```vim
" autoload/ctrlspace/workspaces.vim (line 347)
set ssop=winsize,tabpages,buffers,sesdir
```

the preserved session options are listed.
Not sure if there's a strong reason to exclude `folds`.
Would you mind trying adding it back?

How about a global `g:CtrlSpaceSessionOptions` list variable to give the user some additional flexibility?
