### ISSUE TITLE
Strange buffer navigating order using `:bn`

### ISSUE THREAD

**Issue by dc3671** [vim-ctrlspace/vim-ctrlspace#232]
**Describe the bug**
There exist four buffer opened with `ctrlspace` function `o`, and when I want to use `:bn` navigating among them, the order is neither same as the opening order nor the sorted order.

**To Reproduce**
1. Open `run.py`, `search.py`, `transform.py`, `evaluate.py`
2. Input `:bn` four times
3. the order is `evaluate.py`->`[No Name]`->`transform.py`->`run.py`->`search.py`

**Expected behavior**
 `evaluate.py`-> `run.py`-> `search.py`-> `transform.py`

Best to navigating as sorted order, or can I config to cancel buffer sort?

**Version(s) (please complete the following information):**
 - OS: [Ubuntu 16]
 - Version [gvim VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)]
 - vim-plugins: `vim-airline/vim-airline`, `mkitt/tabline.vim`

**Comment by cometsong** [comment]
Does this `:bn` act the same when the files are opened from the command line? 
e.g. `gvim run.py search.py transform.py evaluate.py`

Does that task then go in the *opening* order?

**Comment by dc3671** [comment]
@cometsong Tried, and the order is the same as above (problem still exists).
And appeared a new problem with this method:
![image](https://user-images.githubusercontent.com/5948851/62017068-da53d680-b1e7-11e9-94a7-9515f257e849.png)
All highlight were gone for `search.py transform.py` (it's not important, never mind)

**Comment by cometsong** [comment]
Hmmm. I can't reproduce this on my machine with either the reported technique `o` technique or the cmd line.
I don't have `gvim` to test with, but i've used vim and macvim and both go through the buffers in the order they were opened.

I've tried this:

1. Start `(m)vim`
2. CtrlSpace, then `o`
3. Select file, hit `space` to open
4. Repeat '3' with other files
5. Input `:bn` four times

The buffers are switched to in the order they are opened.

**Comment by dc3671** [comment]
@cometsong Fine... I tried on another machine and not reproduced either. Can I cancel buffer sort and make the list as opened?

**Comment by cometsong** [comment]
Yep, that's an excellent idea for both a config option as well as a keypress toggle sort method by name or by index.  Both sorting functions pre-exist in the `engine.vim` file, but the calls to them are hard-coded in the `buffers` list by name and the `tab` list by index.

I'm labeling this as enhancement for now (_and of course a PR is welcome_ 😃).
As I'd also use this option, it's definitely on the short list.  We can set the "default" listing methods and make a config option for both tab and buffer lists per user, then add in a toggle keymap for altering on the fly.
