### ISSUE TITLE
Is this project ready to be used?

### ISSUE THREAD

**Issue by TC72** [vim-ctrlspace/vim-ctrlspace#244]
This plugin was recommended to me by a reddit poster but I've found it impossible to use and have to wonder if it's broken or is it ready for people to use?

Non stop issues on top of terrible documentation. I tried to start working with some tabs and created a bookmark and a workspace.

I then tried to create a bookmark but it brought over all the files from the previous bookmark. I tried to create a new workspace and it complained it had no project root even though the project did, I confirmed this in the .cs_cache file.

I tried to go back to my first bookmark. I press cr on my chosen bookmark it tells me the CWD has changed and then puts me into one of your modes, there's a single dot, I guess Buffer Single Mode? All I see is a [1*No Name] so I hit <r again. Then I load my previous workspace and I'm back in buffer mode again and have to hit cr to edit a file.

Now I try to go back to a bookmark I created for my vim config files. I'm shown buffer mode and it's offering me a file from the previous bookmark, why? I think OK, maybe I'm doing this wrong, I should just hit w to choose the workspace. So I go back and fore between the bookmarks trying things then get:
E211: File "administrator/components/com_my4g/tables/customer.php" no longer available

Again, OK maybe I've confused it. I go to bookmarks, choose a project, it shows me buffer mode, I press w and pick a workspace, I then get 2 error messages about file not available followed by:
W13: Warning: File "administrator/components/com_my4g/tables/customer.php" has been created after editing started

I've now spent about 4 hours trying to get this plugin to work and I've reached the conclusion that it's not ready for people to be using yet. Maybe mark it as a beta so people know it's not ready?

**Comment by jyscao** [comment]
It's most definitely not in beta and ready you use.

I found these 3rd party docs to be decent: https://atlas-vim.readthedocs.io/vim/plugged/vim-ctrlspace/README/
Though keep in mind, some shortcuts in there might be a bit out of date

**Comment by cometsong** [comment]
@jyscao Great link to that tutorial style article.  

Perhaps we can "*convert*" that to some wiki pages (or vimdocs) here a for more detailed as well as *current* walkthrough of way to setup the plugin.
