### ISSUE TITLE
Cannot map `<return>` in `g:CtrlSpaceKeys`

### ISSUE THREAD

**Issue by adithyaov** [vim-ctrlspace/vim-ctrlspace#249]
**Describe the bug**
I'm unable to map `<return>` in `g:CtrlSpaceKeys`.

**To Reproduce**
1. Put this in your configuration:
```
function! SayHello()
  echo "Hello!"
endfunction

let g:CtrlSpaceKeys = { "Buffer": { "<return>": "SayHello" } }
```
2. Source your configuration.
3. Open the buffer list and press `<return>`. (Enter)
4. Does not echo "Hello".

**Expected behavior**
Should echo "Hello"

**Screenshots**
None

**Version(s) (please complete the following information):**
 - OS: linux
 - Version: nvim v0.3.5

**Additional context**
None

**Comment by Konfekt** [comment]
I think for this to work, looking at
```vim
" autoload/ctrlspace/keys.vim (lines 65-68)
let specials = "Space CR BS Tab S-Tab / ? ; : , . < > [ ] { } ( ) ' ` ~ + - _ = ! @ # $ % ^ & * C-f C-b C-u C-d C-h C-w " .
             \ "Bar BSlash MouseDown MouseUp LeftDrag LeftRelease 2-LeftMouse " .
             \ "Down Up Home End Left Right PageUp PageDown " .
             \ 'F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12 "'
```
rather `CR` instead of `Return` has to be tried. If this goes through, then perhaps `Return` should be added to this list if this doesn't clobber anything.

**Comment by cometsong** [comment]
As a side note, re-`sourcing` your config does not map new key values; you'd need to restart vim to re-do the ctrlspace init function.  `autoload/ctrlspace/init.vim#L38` is the only place it's called.

Mapping 'return' doesn't work, CR does; adding 'return' to the "specials" might be a way to allow that. 

See #248 for other techniques.

**Comment by Konfekt** [comment]
> adding 'return' to the "specials" might be a way to allow that.

Then we have to be on guard, for example, for any checks if `<CR>` has not been mapped yet (but `<Return>` has!). Not sure if it's worth it, because `<return>` as a synonym for `<CR>` seems uncommon. If so, then for example `<Backspace>` instead of `<BS>` is another synonym.
