### ISSUE TITLE
CtrlSpaceGo* commands do not trigger BufEnter event

### ISSUE THREAD

**Issue by adithyaov** [vim-ctrlspace/vim-ctrlspace#251]
**Describe the bug**
`CtrlSpaceGoUp` and `CtrlSpaceGoDown` do not trigger the BufEnter event.

**To Reproduce**
1. Put this in your `.vimrc`: `autocmd! BufEnter * echo "Hello World!"`
2. Open some buffers in the same tab
3. Execute the command `CtrlSpaceGoUp` or `CtrlSpaceGoDown` (eg `:CtrlSpaceGoDown<cr>`)

**Expected behavior**
"Hello World!" should be echoed.

**Screenshots**

**Version(s) (please complete the following information):**
 - OS: linux
 - Version: nvim v0.3.5

**Additional context**

**Comment by Konfekt** [comment]
The autocommands are triggered, but
```vim
" autoload/ctrlspace/window.vim (line 126)
silent! exe ":b " . bufferList[targetIndex]["index"]
```
shows that output on entering the buffer is suppressed, see `:help :silent`.

Instead `autocmd! BufEnter * vsplit` or any other command show that they are triggered indeed.

**Comment by adithyaov** [comment]
Ah, I see. Thank you for replying @Konfekt :-)
