### ISSUE TITLE
1st March changes makes it fail to load in Noevim

### ISSUE THREAD

**Issue by unclechu** [vim-ctrlspace/vim-ctrlspace#260]
**Describe the bug**

After latest update to b2e1d7659d19e4aaab2413c7278d3b551a0e0b9c (1st March) it fails to load in Neovim. Errors are about some functions are failed to be redefined.

I [rolled back](https://github.com/unclechu/neovimrc/commit/72680c7f66f6d4a1864b5f3be08aefd3ca2a1da5) to 88da905 and everything works fine for me.

So it must be it's either cdf22f85e0bd448ee0db801663fb7c66b4ff20f9 or b2e1d7659d19e4aaab2413c7278d3b551a0e0b9c which involves this errors (or maybe even both, third commit of 1st Mach changes only meta info, readme files, etc.).

**To Reproduce**
Just run Neovim.

**Expected behavior**
Neovim runs without any failures.

**Screenshots**
![Screenshot from 2020-03-02 15-22-10](https://user-images.githubusercontent.com/799353/75680222-c7cbdf00-5c99-11ea-9744-b23cd90b9a14.png)

**Version(s) (please complete the following information):**
 - OS: Fedora Workstation 30 (GNU/Linux kernel: `5.5.5-200.fc31.x86_64` fetched from Fedora 31's repo)
 - Version [Neovim nightly 2020-02-28](https://github.com/neovim/neovim/commit/49cd750d6) `v0.5.0-404-g49cd750d6`

**Comment by luozhy** [comment]
The same problem after update to b2e1d76
Rolled back to 88da905 is fine


- OS: Linux ubuntu18 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- VIM Version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)
- Screenshots:
![image](https://user-images.githubusercontent.com/34363808/75697296-d2ad6080-5ce7-11ea-9fdd-06d35370048e.png)


- OS: Linux CentOS8 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- VIM Version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 11 2019 19:08:24)
- Screenshots:
![image](https://user-images.githubusercontent.com/34363808/75698708-2ae56200-5cea-11ea-82c3-edd22f10a4a2.png)

**Comment by unclechu** [comment]
@luozhy Thanks for your feedback! Now we can assume that this bug isn't related to Neovim or its nightly release only.

**Comment by unclechu** [comment]
I left a [comment](https://github.com/vim-ctrlspace/vim-ctrlspace/commit/cdf22f85e0bd448ee0db801663fb7c66b4ff20f9#r37598155) under suspicious line of code in cdf22f8.

**Comment by unclechu** [comment]
Anyway, I realized that piece of code wasn't the reason of why it fails.

**Comment by unclechu** [comment]
But I also realized that the bug appears exactly since cdf22f85e0bd448ee0db801663fb7c66b4ff20f9

**Comment by unclechu** [comment]
I was a bit blind, there's [extra `endif`](https://github.com/vim-ctrlspace/vim-ctrlspace/commit/cdf22f85e0bd448ee0db801663fb7c66b4ff20f9#r37599378) which breaks syntax.

**Comment by unclechu** [comment]
And that extra `endif` isn't even the problem :man_facepalming: 

But I found what causes this. [This line](https://github.com/vim-ctrlspace/vim-ctrlspace/commit/cdf22f85e0bd448ee0db801663fb7c66b4ff20f9#diff-649179930d075ce6c23310d4d3abc857R115) it seems that my config is calling ctrlspace for generating tabline and `ctrlspace#util#system` isn't defined yet.

**Comment by unclechu** [comment]
And it's hard to resolve, because `autoload/ctrlspace/util.vim` statically depends on `ctrlspace#context#Configuration` thus on `autoload/ctrlspace/context.vim` (circular dependency).

**Comment by unclechu** [comment]
#261 fixes this bug.

**Comment by adelarsq** [comment]
I'm using this config on Plug for now:

        Plug 'https://github.com/vim-ctrlspace/vim-ctrlspace', {'commit':'58dde8ad1163856903a00f390330474007fb9f69'}
