### ISSUE TITLE
Release 5.0.1

### ISSUE THREAD

**Issue by Konfekt** [vim-ctrlspace/vim-ctrlspace#270]
Since the release of version 5 some time has passed. How about tagging a bug fix release 5.0.1 after merging all pull requests?

**Comment by jyscao** [comment]
This is a good point. I presume the versions are carried over from back when the plugin was under the profile of the original author? Because as of right now, I find no tags in `git log` other than the one labeled `all_os_file_engines`.

Going forward, I'd definitely like us to go be more consistent wrt maintenance and updates.

**Comment by Konfekt** [comment]
Yes, they are carried over and no version tags in git were given. So 5.0.1 would be the starting point.

**Comment by jyscao** [comment]
Actually if you take a look at `ctrlspace.txt`, it says it's at 5.0.7

So perhaps after taking care of some of the in-progress issues/PRs, we can increment to 5.1.0, since there has been a couple minor features added since then.

**Comment by Konfekt** [comment]
Yeah, perfect.

**Comment by Konfekt** [comment]
@jyscao, How about a 5.1 release in the near future?

**Comment by jyscao** [comment]
@Konfekt yes, we definitely should. What do you have in mind? Just tag HEAD of master as 5.1 perhaps?

**Comment by Konfekt** [comment]
Exactly

**Comment by Konfekt** [comment]
What title and description?
Mind that the last commit by @szw has been almost seven years ago: https://github.com/vim-ctrlspace/vim-ctrlspace/commit/f7987e4e21b238732632be704d033a73aacbb65d

Various bug fixes, in particular adjustments for Neovim, uncoupling of binaries, rewrite of the documentation / Readme, ...

**Comment by jyscao** [comment]
Sorry for not getting back to you earlier. Why don't you take point on getting this release out. I haven't been able to hack on this much the last long while due to the day job, but that will soon change in the upcoming month or two.

**Comment by Konfekt** [comment]
I went ahead and tagged @szw 's last contribution as 5.0.1 to see the additions of his sucessors

**Comment by Konfekt** [comment]
Oh... it's 5.0.7. I correct
