### ISSUE TITLE
vim :bdelete drops tab with all associated buffers

### ISSUE THREAD

**Issue by ezinder** [vim-ctrlspace/vim-ctrlspace#275]
**Describe the bug**
Using :bdelete in a tab, closes the tab despite having multiple associated buffers in the same tab.

**To Reproduce**
1. Create a new tab 
2. Add multiple files / buffers to the tab 
3. run :bdelete  in command mode

**Expected behavior**
The buffer should be either detached from the tab, or deleted - but the tab (and all associated buffers) should remain open.  
If that's not possible, then at least expose an API for "ctrlspace#keys#buffer#DetachBuffer" so it is accessible to vim bindings 

**Additional context**
:version                                                                                                                                                 
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5

**Comment by jyscao** [comment]
@ezinder Please use the suggestions provided in #218
