### ISSUE TITLE
API for ctrlspace#keys#buffer#DetachBuffer

### ISSUE THREAD

**Issue by ezinder** [vim-ctrlspace/vim-ctrlspace#276]
Could you please expose "ctrlspace#keys#buffer#DetachBuffer" as an API endpoint like you did with :CtrlSpaceGoDown and :CtrlSpaceGoUp ?   

When using vim's native tabs / windows, I can cycle through buffers and drop unused buffers with :bd, while the tab/window structure remains unchanged.   However, with CtrlSpace installed, a tab holding multiple buffers will close if :bd command is issued.  I've got :bn/:bp and :bd bound to trigger-happy key bindings and it's second nature for me to "delete" a buffer from a tab.  I can't break that habit :(.

**Comment by jyscao** [comment]
@ezinder As mentioned in #275 try out the aforementioned workarounds for now.

If still unsatisfactory, and you'd really like `ctrlspace#keys#buffer#DetachBuffer` to be exposed so you can create your own mappings with it, then we could discuss and consider doing so. But only as part of a broader effort to review and revise the entire plugin's public and private API set, which tbh is simply not a priority atm.
