### ISSUE TITLE
Some commands fail with "Undefined variable: idx"

### ISSUE THREAD

**Issue by bodograumann** [vim-ctrlspace/vim-ctrlspace#286]
**Describe the bug**
When using `e` or `y` in the buffer list I get the following error:

> Error detected while processing function ctrlspace#keys#Keypressed[14]..ctrlspace#keys#file#CopyFileOrBuffer[1]..ctrlspace#files#CopyFileOrBuffer[7]..<SNR>120_get_selected_file_or_buff:
> line    2:
> E121: Undefined variable: idx
> E116: Invalid arguments for function bufname(idx)), a:mod)
> E116: Invalid arguments for function resolve(bufname(idx)), a:mod)
> E116: Invalid arguments for function fnamemodify(s:modes.File.Enabled ? file : resolve(bufname(idx)), a:mod)    

**To Reproduce**
1. Open ctrlspace bar
2. Press `e`

**Version(s) (please complete the following information):**
 - OS: linux
 - Version gvim 8.2 / 1-1989
 - master branch of ctrlspace

**Additional context**
Maybe you accidentally pushed a broken WIP to the master branch?

**Comment by Konfekt** [comment]
Yes, somehow `idx` is undefined at 

```vim
" autoload/ctrlspace/files.vim (line 23)
function! s:get_selected_file_or_buff(mod) abort
```

**Comment by Konfekt** [comment]
@jyscao Probably just missing an initial line

```vim
let idx = ctrlspace#window#SelectedIndex()
```

**Comment by jyscao** [comment]
@bodograumann sorry, just noticed this now. And yes, this is definitely a goof caused by the new feature I added. I'll fix this asap

**Comment by jyscao** [comment]
@bodograumann just pushed the fix, should be good now

@Konfekt that indeed was the problem. However while doing the initial debugging I stumbled upon a related bug, hence my not immediately applying your suggested fix. What happens is that the files list held by the `s:Cache` object was not being populated when the editor and plugin are first loaded, thus even with `idx` defined, Vim throws an index out of bounds error. This is also fixed now.

**Comment by bodograumann** [comment]
I now get different errors. When using `i`:

> Error detected while processing function ctrlspace#keys#Keypressed[14]..ctrlspace#keys#file#GoToDirectory[1]..ctrlspace#files#GoToDirectory[12]..<SNR>119_get_selected_file_or_buff[2]..<SNR>119_get_selected_file[7]..function ctrlspace#keys#Keypressed[14]..ctrlspace#keys#file#GoToDirectory[1]..ctrlspace#files#GoToDirect
> ory[12]..<SNR>119_get_selected_file_or_buff[2]..<SNR>119_get_selected_file:
> line    6:
> E684: list index out of range: 23
> Error detected while processing function ctrlspace#keys#Keypressed[14]..ctrlspace#keys#file#GoToDirectory[1]..ctrlspace#files#GoToDirectory:
> line   12:
> E171: Missing :endif

When pressing `e` or `y`:

> Error detected while processing function ctrlspace#keys#Keypressed[14]..ctrlspace#keys#file#EditFile[1]..ctrlspace#files#EditFile[1]..<SNR>119_get_selected_file_or_buff[2]..<SNR>119_get_selected_file[7]..function ctrlspace#keys#Keypressed[14]..ctrlspace#keys#file#EditFile[1]..ctrlspace#files#EditFile[1]..<SNR>119_get_
> selected_file_or_buff[2]..<SNR>119_get_selected_file:
> line    6:
> E684: list index out of range: 23

**Comment by jyscao** [comment]
I tried to reproduce in a new editor session, press `<ctrl>`+`<space>` then one of `e`, `y` and `i`, and all are working normally for me.

Can you provide more detailed steps to reproduce?

**Comment by jyscao** [comment]
@bodograumann I have a hunch of what the problem might be for you. Try refreshing your file cache first, then invoke one of those keys.

I will try to implement a better fix to this.

**Comment by jyscao** [comment]
@bodograumann I pushed a better fix for this issue. Please test and let me know.

**Comment by bodograumann** [comment]
Yes! Now it is working perfectly again.
Thank you for the fix. :heart:
