### ISSUE TITLE
CtrlSpace tries to open workspace when quitting

### ISSUE THREAD

**Issue by erratic-c-programmer** [vim-ctrlspace/vim-ctrlspace#287]
When exiting vim, CtrlSpace seems to want to open the workspace in the current directory just before quitting.
Usually this isn't much of a problem, but when you open a second instance of vim in the same directory to do a quick edit
to a file and then :wq, this happens:
```
Error detected while processing .../CS_SESSION:
line   24:
E325: ATTENTION
Found a swap file by the name "..."
          owned by: ...   dated: Thu Dec 10 11:51:32 2020
         file name: ...
          modified: no
         user name: ...   host name: ...
        process ID: 9683 (STILL RUNNING)
While opening file "..."
             dated: Wed Dec 09 21:29:45 2020

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r ..."
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "..."
    to avoid this message.
```

**To Reproduce**
1. Go to a directory
2. Open some files ans make some edits
3. Save the workspace
4. Open a new instance of the terminal
5. Go to that directory
6. Open another instance of vim and create a new file
7. Edit
8. ```:wq```

**Expected behavior**
It should just quit

**Version(s) (please complete the following information):**
 - OS: Linux
 - Version NVIM v0.5.0-ef3230f

**Comment by jyscao** [comment]
I will look into this bug, likely over the weekend.

In the meantime, does this problem also occur if you use CtrlSpace's built-in mapping to quit (i.e. `Q` from within any of its list modes)?

**Comment by Konfekt** [comment]
If `g:CtrlSpaceSaveWorkspaceOnExit` is set, then indeed the workspace is saved by

```vim
" autoload/ctrlspace/init.vim (lines 62-64)
if s:config.SaveWorkspaceOnExit
    autocmd CtrlSpaceInit VimLeavePre * if ctrlspace#workspaces#ActiveWorkspace().Status | call ctrlspace#workspaces#SaveWorkspace("") | endif
endif
```

**Comment by Konfekt** [comment]
If `g:CtrlSpaceSaveWorkspaceOnExit` is set, then indeed the workspace is saved by

```vim
" autoload/ctrlspace/init.vim (lines 62-64)
if s:config.SaveWorkspaceOnExit
    autocmd CtrlSpaceInit VimLeavePre * if ctrlspace#workspaces#ActiveWorkspace().Status | call ctrlspace#workspaces#SaveWorkspace("") | endif
endif
```

**Comment by erratic-c-programmer** [comment]
> I will look into this bug, likely over the weekend.
> 
> In the meantime, does this problem also occur if you use CtrlSpace's built-in mapping to quit (i.e. `Q` from within any of its list modes)?

Yes

**Comment by erratic-c-programmer** [comment]
It seems to be an odd issue with my config... sorry
