### ISSUE TITLE
Commit 0c9fef8 breaks fuzzy finding file feature for newly created directory

### ISSUE THREAD

**Issue by toasterbath255** [vim-ctrlspace/vim-ctrlspace#288]
**Describe the bug**
Commit 0c9fef80d6fd616d30910c567f74210b1d90d95f breaks fuzzy finding file feature for newly created directory.

**To Reproduce**
1. make new directory
2. add some files
3. add project root
4. invoke `:CtrlSpace O`

**Expected behavior**
list files as usual

**Screenshots**
![error](https://user-images.githubusercontent.com/66874440/103718612-8408db00-500a-11eb-9343-a286680d414f.png)

**Version(s) (please complete the following information):**
 - OS: Archlinux
 - Version: Neovim v0.4.4

**Additional context**
If I revert to 7015f2488269b9c101161d31f7525787418fd05a, it works just as usual. And already existing project roots are still working too.

**Comment by jyscao** [comment]
Apologies about the breakage, should be fixed now if you pull.
