### ISSUE TITLE
Allow quick toggling between last buffer and current buffer 

### ISSUE THREAD

**Issue by ldelossa** [vim-ctrlspace/vim-ctrlspace#289]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When opening a per-tab buffer list, the "previously acceded" buffer should be the where the cursor lands. This will allow a quick ";<cr>" to toggle between two buffers.

**Describe alternatives you've considered**
None so far.

**Version(s) (please complete the following information):**
 - OS: Linux
 - Version: Vim8

**Comment by Konfekt** [comment]
Selecting the last used instead of the currently used buffer by default is unintuitive. 

Does a mapping such as

```vim
nnoremap <silent> ;   :<c-u>CtrlSpace P<CR>
```

fulfill your request?

**Comment by ldelossa** [comment]
Let me give this a try. 

Tools like fzf tend to do this "cursor on previously visited buffer" so you can quickly switch between two buffers. However, fzf does not really expect you to manipulate any of the items within the preview window. So I can see your point on non intuitive, however I'm so used to the quick toggle of provided by fzf and ctrl-p.

**Comment by ldelossa** [comment]
I'd still generally like the menu to open, which this mapping doesn't accomplish. 

If the opinion is, that this is now how ctrlspace is expected to behave, that if fair enough.

**Comment by Konfekt** [comment]
Okay, then what you look for is 

```vim
nnoremap <silent> ;   :<c-u>CtrlSpace p<CR>
```

with a minuscule `p`.

**Comment by ldelossa** [comment]
that seems to work for me. Thanks a lot. 

Is it normal to have to hit enter twice to select the buffer?

**Comment by Konfekt** [comment]
No, it is not. When you say select, you mean open? Hitting `;<CR>` opens the previous buffer over here on Vim 8.0.1560 with the latest main branch of vim-ctrlspace.

**Comment by ldelossa** [comment]
your solution works great. thanks a lot.
