### ISSUE TITLE
Don't sort the bufferlist for vim-airline

### ISSUE THREAD

**Issue by DanielLaszlo** [vim-ctrlspace/vim-ctrlspace#291]
Hi,

I've just started using ctrlspace recently, and I love it so far!
Unfortunately  sorting the bufferlist by name here
https://github.com/vim-ctrlspace/vim-ctrlspace/blob/6737bfabee7ed99a97c0067227fb8905eaf7853c/autoload/ctrlspace/api.vim#L27
makes using :bprevious and :bnext really unintuitive with vim-airline.
I have these mappings in my vimrc:
nnoremap <c-h> :bprevious<CR>
nnoremap <c-l> :bnext<CR>

In my workflow I relied on the order in which the files were opened, but that doesn't work with CtrlSpace and vim-airline anymore. 

Is there a workaround for this?

**Comment by jyscao** [comment]
I don't use vim-airline personally, so can't say I'm entirely sure what they behavior you're looking for is yet. But if you're using `:bn` and `:bp` to navigate b/w opened buffers, doesn't that break the built-in tab organization in cltrspace?

In any case, can you try commenting out that line you suspect is creating the problem for you, and see if that makes a difference? You should also try replacing it with `call sort(bufferList, function("ctrlspace#engine#CompareByIndex"))` and see if that does anything.

I'd tried both, and wasn't able to discern a difference in behavior from the current implementation. Which brings me back to my original point that I don't fully understand what you're looking for. So please elaborate, and I'll do my best to help.

**Comment by DanielLaszlo** [comment]
Hi @jyscao,

Is there a built-in way in CtrlSpace to quickly switch between neighbouring buffers, that has a similar effect as :bn and :bp? 

An example when my issue occurred:
`vim d c a b`

The problem was that the buffers were ordered alphabetically in the tabline by vim-airline `( a | b | c | d )`, not by their index `( d | c | a | b )`

`ctrlspace#engine#CompareByIndex` solves the issue, i.e. the tabline showed `( d | c  | a | b )`

I dug a little further and it seems like I was using an old commit of vim-airline (https://github.com/vim-airline/vim-airline/commit/9614105d09ff0d6e1043ab33028615f107fe94a5)

Pulling the latest vim-airline (and reverting `CompareByIndex` to `CompareByText` also solves the issue.

Thanks for the help!
