### ISSUE TITLE
File Engine Error

### ISSUE THREAD

**Issue by erikc96** [vim-ctrlspace/vim-ctrlspace#292]
**Describe the bug**
I was following the getting started steps in the README. I created a bookmark, and hit the 'o' key to open it, and received an error.

**To Reproduce**
1. Hit <C-Space>
2. Hit 'o'

**Expected behavior**
It to open the directory.

**Screenshots**

Error detected while processing function ctrlspace#keys#Keypressed[14]..ctrlspace#keys#common#ToggleFileMode[5]..<SNR>127_toggleListView[18]..ctrlspace#window#Toggle[52]..ctrlspace#engine#Content[2]..<SNR>174_contentFromFileEngine:
line   10:
E684: list index out of range: 1
E116: Invalid arguments for function eval(results[1])
Error detected while processing function ctrlspace#keys#Keypressed[14]..ctrlspace#keys#common#ToggleFileMode[5]..<SNR>127_toggleListView[18]..ctrlspace#window#Toggle:
line   52:
E714: List required

**Version(s) (please complete the following information):**
 - OS: OSX m1
 - Version  ⌗ CtrlSpace 5.0.7 (engine: VIM), Vim version 8.2. 

**Additional context*

**Comment by jyscao** [comment]
@erikc96 sorry for the late follow up, I finally got some free time to look into this now.

Can you elaborate a bit more on the problem you're running into, because I can't say I understand what you meant. The bookmark mode is activated with `b`, which I tested just now and was able to create fine. But you're saying that `o`, which is files list mode isn't working for you? Those 2 modes shouldn't be related.

**Comment by crowdigit** [comment]
I had similar issue and I can reproduce the error.

My error log:
```
Error detected while processing function ctrlspace#keys#Keypressed[14]..ctrlspace#keys#common#ToggleFileModeAndSearch[1]..<SNR>90_toggleListViewAndSearch[2]..ctrlspace#k
eys#common#ToggleFileMode[5]..<SNR>90_toggleListView[18]..ctrlspace#window#Toggle[57]..ctrlspace#engine#Content[2]..<SNR>128_contentFromFileEngine:                      
line    9:                                                                                                                                                               
E684: list index out of range: 0                                                                                                                                         
E116: Invalid arguments for function eval                                                                                                                                
E15: Invalid expression: eval(results[0])                                                                                                                                
Error detected while processing function ctrlspace#keys#Keypressed[14]..ctrlspace#keys#common#ToggleFileModeAndSearch[1]..<SNR>90_toggleListViewAndSearch[2]..ctrlspace#k
eys#common#ToggleFileMode[5]..<SNR>90_toggleListView[18]..ctrlspace#window#Toggle:                                                                                       
line   57:                                                                                                                                                               
E714: List required                                                                                                                                                      
1 line less; before #1  5 seconds ago                                                                                                                                    
                                                                                                                                                                         
Press ENTER or type command to continue 
```

I'm using M1, CtrlSpace 5.0.7 (engine: VIM)

Few things to note
1. This error does not occur if I set `g:CtrlSpaceFileEngine` to anything other than `VIM`
2. Setting `let g:CtrlSpaceEnableFilesCache = 0` also prevents this error
3. I tried this on linux desktop and I can reproduce it

So, to reproduce the error,

1. Use the default file engine
2. Use file caching (`let g:CtrlSpaceEnableFilesCache = 1`)
3. Just `cd` to any directory and hit `Ctrl-P` (list all files in CtrlSpace buffer) and you get the error
4. On directories that are not git repository, it may prompts to set root directory, hitting enter produces the error anyway

**Comment by crowdigit** [comment]
I could fix this issue by compiling file engine by myself. To do that,

1. clone this repository
2. build file engine
3. copy binary file
4. edit `init.nvim`

```bash
# clone
git clone git@github.com:vim-ctrlspace/vim-ctrlspace.git

# build
cd vim-ctrlspace/go
go build ./file_engine.go

# copy
cp ./file_engine ~/.config/nvim/pack/minpac/start/vim-ctrlspace/bin/file_engine_darwin_arm
# I named new binary 'file_engine_darwin_arm'
# copy where your vim-ctrlspace is installed, I'm using minpac
```

Open vim config file and set `g:CtrlSpaceFileEngine` to binary name set above, in this example `file_engine_darwin_arm`

```vim
let g:CtrlSpaceFileEngine = 'file_engine_darwin_arm'
```

I think this issue occurs because binary for M1 does not included and vim implementation is not working well for M1, I guess.

Including binary for M1 and detecting M1 environment feature may fix this issue I guess.

**Comment by jyscao** [comment]
@crowdigit nice work on both reproducing the issue and figuring out the cause and fix. I compiled and added the binary for darwin_arm in [the latest commit](https://github.com/vim-ctrlspace/vim-ctrlspace/commit/ded93959d346780eed45fd91784b2d4818044553)
