### ISSUE TITLE
Workspace load/save only works for 1st TabList

### ISSUE THREAD

**Issue by GregoireHENRY** [vim-ctrlspace/vim-ctrlspace#293]
**Describe the bug**
For a workspace with 2 or more tablist, only the 1st tablist loads successfully. This includes, the label of the tablist, and the buffers linked to the tablist.
From the 2nd to the last tablist, only the last buffer opened of the tablist is loaded and the tablist has the name of the buffer.

Buffers are still saved in the workspace, they can be accessed with ":ls". They are just not linked anymore with the tablist.

**To Reproduce**
1. Create workspace of 2 tablists with 2 unique buffers on each tablist.
3. Save workspace and exit neovim
4. Open neovim, load workspace, and see the problem in the tablists

**Expected behavior**
Labels of tablists and buffers list in tablists must be found again (when workspace is loaded) as they were when the workspace was saved.

**Screenshots**
Demo.
![Peek 2021-03-25 17-41](https://user-images.githubusercontent.com/45257753/112510777-0c895300-8d92-11eb-95d6-9f4f43e132f8.gif)

The .cs_workspace in text file if you want to read it, I don't know it it can be useful or not.
[cs_workspaces.txt](https://github.com/vim-ctrlspace/vim-ctrlspace/files/6206421/cs_workspaces.txt)

The verbose if you also want.
[verbose-cs-workspace-nvim.log](https://github.com/vim-ctrlspace/vim-ctrlspace/files/6206534/verbose-cs-workspace-nvim.log)

**Version(s) (please complete the following information):**
 - OS: linux ubuntu 20
 - Version NVIM v0.5.0-dev

**Additional context**
Of course before writing this one I read:

+ [issue 290](https://github.com/vim-ctrlspace/vim-ctrlspace/issues/290): same label problem and the latest similar issue, but without the problem of the buffer links missing, and no news since early Feb
+ [issue 264](https://github.com/vim-ctrlspace/vim-ctrlspace/issues/264): very short thread redirecting other toward issues
+ [issue 238](https://github.com/vim-ctrlspace/vim-ctrlspace/issues/238): similar, old, unsolved
+ [issue 230](https://github.com/vim-ctrlspace/vim-ctrlspace/issues/230): similar, interesting, unsolved, old

I followed all advices in these issues, for example I minimized my neovim config to only have this plugin and the options to make it run. I observed no good result. Is it just the version of neovim that does not match?
This issue is particularly irritating, but otherwise the plugin is just awesome and what you guys did is just the future. I really hope this will be solved.
What could I do to help you solve this one?
Cheers

**Comment by Konfekt** [comment]
Thank you! Since I  could not reproduce it in Vim, could you check if this issue persists in Vim? 

It might be that Nvim does something different from Vim that we do not know of. Maybe it is simply that `patch-8.1.149` has not been ported, or the check for its existence does not work in Nvim?

**Comment by Konfekt** [comment]
It might simply be due to https://github.com/neovim/neovim/issues/9635

Thus, if Nvim has patch-8.1.149, then change in `autoload/ctrlspace/workspaces.vim` (lines 388-429)

```
elseif
    \    ((cmd =~# '^edit \f\+') && (tabIndex == 0))
    \ || (!has('patch-8.1.149') && cmd =~# '^tabedit \f\+')
    \ || ( has('patch-8.1.149') && cmd ==# 'tabnext')
```

to

```
elseif
    \    ((cmd =~# '^edit \f\+') && (tabIndex == 0)
    \ || cmd ==# 'tabnext')
```

or, if not, then to

```
elseif
    \    ((cmd =~# '^edit \f\+') && (tabIndex == 0))
    \ || cmd =~# '^tabedit \f\+')
```

**Comment by Konfekt** [comment]
We can then add a check for Nvim accordingly.

**Comment by Konfekt** [comment]
I think I pinned down the commit that recently ported the patch to Nvim and now check for version 0.5 accordingly.

**Comment by GregoireHENRY** [comment]
> Thank you! Since I could not reproduce it in Vim, could you check if this issue persists in Vim?
> 
> It might be that Nvim does something different from Vim that we do not know of. Maybe it is simply that `patch-8.1.149` has not been ported, or the check for its existence does not work in Nvim?

Hello Konfekt, thank you for your very fast reply, I appreciate it a lot!
Actually vim was not setup on my computer hahah, I was only using neovim, I set it up with the minimal required configuration as you can see:

![Screenshot from 2021-03-27 11-17-57](https://user-images.githubusercontent.com/45257753/112717600-2a6bca80-8eee-11eb-8011-2a4afc148a81.png)

I have installed this version: `VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 21 2021 21:02:22) Included patches: 1-2539`

Here is the new demo, but it is failing again, and not with the same results.

![Peek 2021-03-27 11-16](https://user-images.githubusercontent.com/45257753/112717678-8b939e00-8eee-11eb-9b72-6a7b2399f31a.gif)

As you can see, this time, with vim, the second tab is fine but the first tab is missing one buffer, and now the buffer is not even in the list of available buffers (`:ls`).

**Comment by GregoireHENRY** [comment]
> It might simply be due to [neovim/neovim#9635](https://github.com/neovim/neovim/issues/9635)
> 
> Thus, if Nvim has patch-8.1.149, then change in `autoload/ctrlspace/workspaces.vim` (lines 388-429)
> 
> ```viml
> elseif
>     \    ((cmd =~# '^edit \f\+') && (tabIndex == 0))
>     \ || (!has('patch-8.1.149') && cmd =~# '^tabedit \f\+')
>     \ || ( has('patch-8.1.149') && cmd ==# 'tabnext')
> ```
> 
> to
> 
> ```viml
> elseif
>     \    ((cmd =~# '^edit \f\+') && (tabIndex == 0)
>     \ || cmd ==# 'tabnext')
> ```
> 
> or, if not, then to
> 
> ```viml
> elseif
>     \    ((cmd =~# '^edit \f\+') && (tabIndex == 0))
>     \ || cmd =~# '^tabedit \f\+')
> ```

I applied the first suggestion you made, and it works!!
The workspace saving and loading system works perfectly as expected with this fix!

Could I ask you how am I supposed to do now? Should I keep the local fix as long as the master branch has not merged this fix and then update the plugin with `:PlugUpdate`?
A huge thanks Konfekt ✨

**Comment by Konfekt** [comment]
You can go `:PlugUpdate vim-ctrlspace` and it will be all fine. The whole issue was about Nvim not having implemented the `has('patch...')` feature.
