### ISSUE TITLE
Open Ctrlspace window from command line buffer will lock the cursor in the window.

### ISSUE THREAD

**Issue by farhanmustar** [vim-ctrlspace/vim-ctrlspace#300]
**Describe the bug**
Hi, I faced bug when opening the buffer list view via ctrl + space while in command line buffer. 

**To Reproduce**
1.  enable command line by pressing colon.
2.  press ctrl + f to open command line buffer.
3.  Enable ctrlspace buffer list window by pressing ctrl + space.
4. Buffer list will show up but will not be able to exit this window.

**Expected behavior**
Command line buffer will be closed and the buffer list will show up properly.

**Version(s) (please complete the following information):**
 - OS: Window (powershell 7) and ubuntu 18.04 (bash)
 - Version vim 8.2

**Comment by Konfekt** [comment]
Thank you for letting us know!
