### ISSUE TITLE
Error loading workspace

### ISSUE THREAD

**Issue by lvim-tech** [vim-ctrlspace/vim-ctrlspace#302]
**Describe the bug**

**To Reproduce**
1. Save bookmarks
2. Save workspace (not found root directory)
3. Manualy set root directory
4. Save workspace
5. Close nvim
6. Open nvim
7. Load bookmark
8. Error loading workspace

**Expected behavior**
It should load my workspace properly.

**Screenshots**
![Screenshot from 2021-09-25 12-27-26](https://user-images.githubusercontent.com/82431193/134766806-1c0c9e83-62fc-4289-904f-8f5e0879b83f.png)

**Version(s) (please complete the following information):**
 - OS: linux - OpenSuse Leap 15.3
 - Version nvim 0.6 dev

**Additional context**
nvim 0.5 - same problem

**Comment by Konfekt** [comment]
Is this latest master of vim-ctrlspace? Line 26 in `s:execWorkspaceCommands` does not load `CS_SESSION`. Make sure to load the workspace with the same commit of vim-ctrlspace with which you saved it.

**Comment by Konfekt** [comment]
The pen-ultimate step, Load bookmark, only changes directory to the bookmarked directory.
Then, over here, loading the saved workspace, say named `ws`, works fine. 

How come with your setup loading the bookmark directly loads a workspace (which one?). (I suspected it due to `let g:CtrlSpaceLoadLastWorkspaceOnStart = 1` but to no avail.)

**Comment by Konfekt** [comment]
As an aside, the last commit should make `let g:CtrlSpaceLoadLastWorkspaceOnStart = 1` work for custom root dirs without repo root markers.

**Comment by Konfekt** [comment]
I decided against loading the last active workspace by default on loading a bookmark (in addition to loading it on Vim startup) if `CtrlSpaceLoadLastWorkspaceOnStart  = 1` because it will break users' expectactions.
