### ISSUE TITLE
CWD not switching upon tab switch

### ISSUE THREAD

**Issue by insipx** [vim-ctrlspace/vim-ctrlspace#305]
**Describe the bug**
When I open one project/bookmark, CWD switches to that project, i open a new tab and open another project in that tab, CWD switches to that project. But when i select previous tab, CWD is still on second project. Does CtrlSpace use `tcd` for managing tab directories or something else? Is it a bug or did i miss something in the workflow

**Expected behavior**
Open two project, CWD switches according to project when switching tabs. Or CWD is set according to tab with `tcd`

**Screenshots**
https://imgur.com/ntor5NZ screencast of the issue

**Version(s) (please complete the following information):**
 - OS: NixOS 22.05
 - Version Neovim v0.8.0-dev (nightly)

**Comment by Konfekt** [comment]
Hello @insipx ,

`vim-ctrlspace` is designed for working with at most one workspace in one instance of Vim.
The CWD is tied to the workspace and is meant to be set for all windows, tabs, globally in

```vim
" autoload/ctrlspace/util.vim (lines 76-97)
function! ctrlspace#util#ChDir(dir) abort
    let dir    = fnameescape(a:dir)
    let curtab = tabpagenr()
    let curwin = winnr()

    silent! exe "cd " . dir

    for t in range(1, tabpagenr("$"))
        silent! exe "noautocmd tabnext " . t

        for w in range(1, winnr("$"))
            silent! exe "noautocmd " . w . "wincmd w"

            if haslocaldir()
                silent! exe "lcd " . dir
            endif
        endfor
    endfor

    silent! exe "noautocmd tabnext " . curtab
    silent! exe "noautocmd " . curwin . "wincmd w"
endfunction
```

So I consider it to be rather a bug.

The session commands are finally loaded in

```vim
" autoload/ctrlspace/workspaces.vim (lines 287-289)
for c in commands
    silent exe c
endfor
```

Could you add the line

```
call ctrlspace#util#ChDir(fnamemodify(".", ":p:h"))
```

afterwards and check back whether the current work dir has become equal in all tab pages?
