### ISSUE TITLE
Filetype not set for additional buffers when multiple files opened

### ISSUE THREAD

**Issue by ruuter** [vim-ctrlspace/vim-ctrlspace#308]
**Describe the bug**
When opening multiple files at once, the filetype is only set for the first buffer.

**To Reproduce**
1. Open multiple files with `vim fileone filetwo`
2. Go to next buffer with `:bn`  or `:CtrlSpaceGoUp`
3. No filetype, no syntax set on any other buffer than the first.

**Expected behavior**
Filetype set on all buffers.

**Version(s):**
 - OS: linux
 - Version: nvim v0.6.1

**Additional context**
Tested with barebones vimrc, with vim -u conf, only plug and ctrlspace loaded. Also with no other plugins, only ctrlspace loaded from nvim packages. Buffers ft is set correctly without and not set if ctrlspace in start dir.

**Comment by Konfekt** [comment]
Hello, thank you for noticing.
This is due to 

```vim
" autoload/ctrlspace/init.vim (line 55)
autocmd CtrlSpaceInit VimEnter * exe 'silent argdo call ctrlspace#buffers#AddBuffer()' | rewind
```

Apparently an `argdo` call, even with no operation, switches off file type detection?!

**Comment by Konfekt** [comment]
Likely `:help argdo` explains why:

```
Note: While this command is executing, the Syntax
			autocommand event is disabled by adding it to
			'eventignore'.  This considerably speeds up editing
			each file.
```

**Comment by Konfekt** [comment]
This seems similar to https://github.com/vim/vim/issues/4761 but is marked resolved. I asked again about it in https://github.com/vim/vim/issues/13058

**Comment by ruuter** [comment]
@Konfekt Superb. It works now. Thanks for quick fix!

**Comment by ruuter** [comment]
@Konfekt Unfortunately, I was too quick to close this. It seems ft is now set on all buffers, but syntax is on only for first two.

**Comment by ruuter** [comment]
To be more precise, `++nested` flag seems to add file type to all buffers, but syntax is set only on first and last.

**Comment by Konfekt** [comment]
Strange, just checked and all buffers are syntax highlighted over here

**Comment by Konfekt** [comment]
... using the same minimal `vimrc` as in the linked thread.

**Comment by ruuter** [comment]
Sorry for delay. Did some more tests in clean docker images:

ubuntu:22.04 vim 2.8
debian:bullseye-slim neovim 0.4.4

Same result. First and last file have syntax on while others do not. Used the same basic .vimrc and 3 simple python files.

```
set nocompatible
autocmd VimEnter * ++nested exe 'silent argdo echo ""' | rewind
filetype plugin indent on
syntax on
set hidden
```

`vim --clean -u .vimrc file1.py file2.py file3.py`

However, as it is not that important, you can easily just `:e` or `:syntax on`, I will close this issue.
Thanks for the quick response anyway!

**Comment by Konfekt** [comment]
Strange, I tried with Vim and Python files, using the mentioned minimal Vimrc, but cannot reproduce. One difference is that you use neovim instead of vim. So maybe rather ask the Neovim maintainers than the Vim maintainers about it?

**Comment by ruuter** [comment]
As I mentioned, I tested on clean ubutnu 22.04 docker container with vim 2.8, not neovim.

```
docker run --rm -it ubuntu:22.04 bash
apt update && apt install vim
```
Copied test files to container and ran the test `vim --clean -u .vimrc file1.py file2.py file3.py`

**Comment by Konfekt** [comment]
Okay, so it is independent of Vim or Neovim. I cannot reproduce on Opensuse; maybe it depends on the files? Say how much time their syntax highlighting takes? I only tested with small Python files.

**Comment by Konfekt** [comment]
Would you mind testing with the latest Vim versions?

**Comment by ruuter** [comment]
No, its not about files. I tested with very simple content and with different files at first. Now all test files contain just:

```python
from datetime import date


def test():
    pass
```

Same happens with NVIM v0.9.2 on ubuntu 18.04 and also same in ubuntu 22.04 docker container with vim  9.0

**Comment by Konfekt** [comment]
I am at loss why I can't reproduce, apart from your minor version being < 9.0.1632.

**Comment by ruuter** [comment]
No worries. I think at this point its not worth chasing it anymore =)

**Comment by Konfekt** [comment]
Maybe 

```
autocmd VimEnter * if argc() > 0|  doautocmd Syntax|  doautocmd FileType |endif
```

at least works around this
