### ISSUE TITLE
Cursor on main buffer is moved when ctrlspace window is toggled

### ISSUE THREAD

**Issue by GeorgeZack** [vim-ctrlspace/vim-ctrlspace#319]
**Describe the bug**
My cursor will move within the main buffer whenever the ctrlspace window is toggled under these conditions:

- When my cursor is below 1/3 of the window size (in my case within 12 lines from the bottom of the window)

I'm using neovim.

**To Reproduce**
1. Open vim
2. Move cursor down near bottom of window (assuming file has more lines that can be displayed at once)
3. Toggle ctrlspace

**Expected behavior**
I expect my cursor position to be preserved. When switching from one buffer to the next, then back again, it can be jarring to move around. Especially when reviewing code quickly back and forth.

**Screenshots**
<details><summary>Before toggling</summary>

![1](https://github.com/vim-ctrlspace/vim-ctrlspace/assets/19842313/7ba9ac5a-aaee-4bdb-b25b-1cbc4e8929e4)

</details>
<details><summary>Toggle on, cursor moves</summary>

![2](https://github.com/vim-ctrlspace/vim-ctrlspace/assets/19842313/142b1a63-cc27-4582-9c85-cfd9b1a48047)

</details>
<details><summary>Toggle off, new cursor position</summary>

![3](https://github.com/vim-ctrlspace/vim-ctrlspace/assets/19842313/fb2641d5-d2b0-43ee-a555-0c9f8a6f7849)

</details>

**Version(s) (please complete the following information):**
 - OS: Artix Linux x86_64, Kernel 6.9.7-artix1-1
 - Version NVIM v0.10.0
 
**Additional context**
Only configuration is:

```
vim.g.CtrlSpaceDefaultMappingKey = '<C-Space> '
```

However, I'm using Airline which has a `ctrlspace` extension. Not sure if that would affect the behavior.

Also, with `trouble` I have a new buffer that is positioned at the bottom of the window and is persistent, it is essentially an LSP diagnostic buffer. When this is toggled on, the bottom 1/3 of the buffer area of ctrlspace cursor bump is changed to almost the entire screen. It makes having the diagnostic up with ctrlspace very difficult to use properly.

**Comment by Konfekt** [comment]
Might it be related to 

```vim
" autoload/ctrlspace/window.vim (lines 97-98)
    normal! zb
endfunction
```

? Does Vim have the same issue?

**Comment by Konfekt** [comment]
Also, I never understood

```
vim.g.CtrlSpaceDefaultMappingKey = '<C-Space> '
```

Does `:CtrlSpace<cr>` have the same issue?

**Comment by GeorgeZack** [comment]
Hi, so sorry for the delay @Konfekt. I'll check this right away. Just wanted to let you know I saw your message.

**Comment by GeorgeZack** [comment]
Misclick

**Comment by GeorgeZack** [comment]
`:CtrlSpace<CR>` still produces the same issue. Commenting `normal! zb` does not fix the issue either.

**Comment by Konfekt** [comment]
Thank you. And on Vim?

**Comment by GeorgeZack** [comment]
It seems to be fine in Vim, not in Neovim tho. In Vim, no cursor movement occurs even without the modifications that you suggested.

**Comment by Konfekt** [comment]
That makes it intricate; in theory vimscript should work the same in both. I'd be happy to have a Neovim expert chime in where Neovim differs so that this could be expected. Otherwise, one needs to distill the exact Neovim bug

**Comment by Konfekt** [comment]
Can you reproduce on Neovim with a minimal `vimrc`?

**Comment by Konfekt** [comment]
Here would be such an example of such a minimal `vimrc`: https://github.com/vim/vim/issues/15152#issuecomment-2212354928

**Comment by Konfekt** [comment]
Maybe check if Airline intervenes first

**Comment by GeorgeZack** [comment]
Ah, minimal vimrc works in neovim. Let me check against airline specifically without touching my other settings.

**Comment by GeorgeZack** [comment]
I'm sorry, should have tested more. Seems like it is an issue with another plugin. This plugin is "edgy". I'll look into this issue more, but ctrlspace is not the issue.

**Comment by GeorgeZack** [comment]
For anyone else with the issue, the option `splitkeep` set to `screen` was the source of the issue. That was enabled during the setup of the other plugin.

**Comment by Konfekt** [comment]
Ah, edgy.nvim it is. Makes sense
