### ISSUE TITLE
vimdiff buffer comparison with the second buffer hidden

### ISSUE THREAD

**Issue by 3ddiddE** [vim-ctrlspace/vim-ctrlspace#323]
**Describe the bug**
When opening two files for comparison in vimdiff, the second buffer will be opened as hidden buffer such that the highlighting for differences will be visible although the buffer is the same for the left and right buffer.
So e.g. when comparing two commits 5601fe2..74b3a19 using git difftool and vimdiff as editor, the commit 5601fe2 will be opened in both views (left and right) instead of opening views for both files.

**To Reproduce**
1. Enable ctrlspace plugin e.g. via vim-plug
2. Open vimdiff e.g. in the ctrlspace repository: git difftool --tool=vimdiff 5601fe2..74b3a19

**Expected behavior**
The buffer on the left should be the file from commit 5601fe2 and the buffer on the right should be the file from commit 74b3a19

**Screenshots**
With ctrlspace **enabled**:
![with-ctrlspace](https://github.com/user-attachments/assets/a628fbf2-7b2b-45e5-b8c0-2074765caa5d)

With ctrlspace **disabled**:
![without-ctrlspace](https://github.com/user-attachments/assets/6da8d45a-087e-4834-a11b-6d6cae2f1718)

**Version(s) (please complete the following information):**
 - OS: linux
 - Version VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Dec 22 2024 21:57:53)

**Comment by 3ddiddE** [comment]
Disabling the hidden option in vim will prevent this, but this option is required by ctrlspace.
Additionally the option itself is not the problem since I can have ctrlspace disabled and the hidden option enabled, and vimdiff will work as expected.
Something happens during initialization of a diff view when ctrlspace is enabled.

**Comment by Konfekt** [comment]
Thank you for pointing this out. The latest commit should have fixed this. Feel free to reopen otherwise
