### ISSUE TITLE
It seems that the WS loading is very slow 

### ISSUE THREAD

**Issue by snowair** [vim-ctrlspace/vim-ctrlspace#6]
Here are some informations:
- Ubuntu 12.10
- GVim 7.4
- Ruby bindings enabled
- Project is a git repo
- My workspace contains 8 Tabs,30 buffers

The workspace loading consumes about 15sec or more!

Other suggestion:
- When saving workspace , we may want to save some session along with the WS(eg. the PWD) .
- Display root path of the workspace on CS status bar.

Thanks for your work!

**Comment by c0ffeeartc** [comment]
Loading workspace was always slow for me - 8 buffers, 4 tabs load over 20 seconds.
Disabling all other plugins made loading instant though.
