### ISSUE TITLE
CtrlP friendly keybindings in search mode

### ISSUE THREAD

**Issue by DXist** [vim-ctrlspace/vim-ctrlspace#79]
It may be a nice idea to support CtrlP-friendly keybindings in search mode. From CtrlP README:

```
Use <c-j>, <c-k> or the arrow keys to navigate the result list.
Use <c-t> or <c-v>, <c-x> to open the selected entry in a new tab or in a new split.
```

It will make transition from CtrlP easier.

**Comment by varmanishant** [comment]
Hey, is it possible to use the arrow keys for navigation?
